#+TITLE:     Méthode de la dissertation philosophique
#+AUTHOR:    Baptiste Mélès
#+EMAIL:     baptiste.meles@gmail.com
#+DATE:      24 août 2022
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  fr
#+OPTIONS:   H:4 num:t toc:3 \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+LATEX_HEADER: \usepackage[frenchb]{babel}
#+LATEX_HEADER: \usepackage{lmodern}
#+LATEX_HEADER: \usepackage{multicol}
#+LATEX_HEADER: \DeclareUnicodeCharacter{00A0}{~}
#+LATEX_HEADER: \DeclareUnicodeCharacter{200B}{}

\bigskip

L'objectif de la dissertation de philosophie est de soulever un problème
sur un sujet donné, et d'y proposer une réponse éclairée.

La présente méthode décrit : 
1. comment rédiger le brouillon (section [[brouillon]]) ;
2. la composition de l'introduction, du développement et de la conclusion
   (sections [[introduction]] à [[conclusion]]) ;
3. un exemple de plan détaillé et de dissertation rédigée
   (sections [[plandetaille]] et [[redaction]]) ;
4. une liste de sujets de dissertation (section [[sujets]]) ; 
5. quelques propositions à destination des enseignants sur la façon
   d'enseigner la méthode de la dissertation.

* Conception du plan détaillé
<<brouillon>>

La composition d'une dissertation a lieu en trois moments : la
conception d'un plan détaillé, la rédaction, la relecture.

** Gestion du temps

Le brouillon est un moment essentiel de la dissertation. Il faut donc
lui consacrer suffisamment de temps, sans pour autant menacer la qualité
de la rédaction.

On dispose généralement de quatre heures en licence pour composer une
dissertation, et de sept heures pour l'agrégation. On doit ménager un
temps important pour la rédaction, car dans la précipitation, il est
presque impossible de réfléchir efficacement. On peut donc consacrer 1h
ou 1h30 au brouillon en licence (donc 2h30 ou 3h pour la rédaction), 3h
pour l'agrégation (donc 4h pour la rédaction).

|---+------------+-----------+-----------+-----------+-------|
|   |            | Brouillon | Rédaction | Relecture | Total |
| / | <          | <         | <         | <         | <>    |
|---+------------+-----------+-----------+-----------+-------|
|   | Licence    | 1h15      | 2h15      | 30 min.   | 4h    |
|   | ENS, Capes | 2h30      | 3h        | 30 min.   | 6h    |
|   | Agrégation | 2h30      | 4h        | 30 min.   | 7h    |
|---+------------+-----------+-----------+-----------+-------|

L'idéal est d'avoir terminé la rédaction avec au moins 15 minutes
d'avance en licence, 30 minutes pour l'agrégation ; on se réserve ainsi
un temps suffisant pour la relecture. 

_Il faut se réserver un temps confortable pour la relecture finale_.
Cette étape cruciale permet de corriger l'orthographe et des lapsus
parfois graves, de rajouter quelques mots ou phrases afin de lever des
ambiguïtés ou d'apporter des précisions. Elle peut permettre de
grappiller un ou deux points précieux[fn:1].

** Problématisation puis accumulation des idées

_Ne commencez surtout pas par accumuler des idées au hasard_. Vous
perdriez du temps en notant des choses inutiles et hors sujet que vous
essaierez de caser à toute force dans la dissertation afin de
rentabiliser l'effort et le temps perdus.

D'abord, _élaborez la définition_ de chacun des termes importants du
point de vue du sens commun. Voir plus bas la section [[definitions]].

Ensuite, _construisez la problématique_ qui permettra de traiter le
sujet. Voir plus bas la section [[problematisation]].

Enfin seulement, _accumulez les idées_ --- thèses, auteurs, références
--- qui seules permettent de répondre à la problématique. Cette dernière
vous donne un critère clair pour exclure toute idée qui serait hors
sujet.


** Composition du plan

Une fois que l'on a suffisamment d'idées et que leur organisation
commence à se préciser dans notre esprit, on peut passer à la
constitution du plan détaillé. Voir un exemple de plan détaillé dans la
section [[plandetaille]].

_Chaque partie du plan doit être formulée par une thèse explicite_, et,
si possible, par des « formules » facilement reconnaissables (on en
trouvera quelques exemples ci-dessous : la substance comme substrat,
comme fiction, ou comme fonction ; la guerre comme déchaînement de
violence, comme violence rationnelle, ou comme violence raisonnable ;
etc.). Voir plus bas la section [[parties]].

Le plan détaillé doit contenir toutes les parties, les sous-parties et
les arguments. _Chaque partie ou sous-partie doit comporter un titre
exprimant la thèse locale_ en quelques mots (par exemple « I - La
substance est un substrat », « A) la substance a un primat
ontologique », « B) la substance a un primat chronologique », « C) la
substance a un primat chronologique », « II - La substance est une
illusion »). Voir plus bas la section [[sousparties]].

Enfin, dans le plan détaillé, on doit noter avec soin la _structure
logique de chacune des transitions_ (voir la section [[transition]]). Cette
précaution garantit que le passage d'une partie à une autre ne sera pas
artificiel ou simplement rhétorique.

** Introduction et conclusion

Une fois le plan terminé, _rédigez intégralement au brouillon
l'introduction et la conclusion_. Ainsi, si vous êtes pris par le temps
en fin de rédaction, vous n'avez plus qu'à recopier la conclusion, et la
dissertation se terminera proprement, même si dans le développement vous
n'avez pas eu le temps d'écrire en détail tout ce que vous espériez.
Voir plus bas les sections [[introduction]] sur l'introduction et [[conclusion]]
sur la conclusion.

Voir un exemple de dissertation rédigée dans la section [[redaction]], que
vous pourrez comparer avec le plan détaillé de la section [[plandetaille]].

* L'introduction
<<introduction>>

L'introduction doit être la présentation, progressive et détaillée, de
la problématique.

_Ne citez pas de noms de philosophes en introduction_ : ceux-ci sont
rigoureusement étrangers à la problématisation de la question, même si
plus tard ils vous seront évidemment très utiles pour proposer des
réponses. Partir de l'état de la littérature philosophique serait
inverser le juste ordre des choses : il faut aller des problèmes à la
philosophie, non de la philosophie aux problèmes. Dans l'introduction
--- comme plus tard dans la conclusion --- l'étudiant doit assumer ses
responsabilités, n'engager que soi, mais s'engager totalement. 

Une introduction est généralement composée des parties suivantes,
chacune pouvant être présentée en un alinéa :

1. l'/amorce/ (déconseillée par l'auteur de ces lignes : voir la
   section [[amorce]]) ;

2. _la /définition/ des termes du sujet_ (voir la section [[definitions]]) ;

3. _la construction de la /tension/_ (en un ou plusieurs paragraphes :
   voir la section [[problematisation]]) ;

4. _la formulation explicite de la /problématique/_ (une question
   unique) ;

5. _l'/annonce du plan/_ (une phrase par partie, chacune étant une
   réponse explicite à la problématique et au sujet : voir la
   section [[annonce]]) ;

6. la présentation des /enjeux/ de cette problématique (fortement
   déconseillée).

Il faut apporter un soin particulier à l'introduction, et plus tard à la
conclusion, car ce sont les deux parties qui marquent le plus les
correcteurs. Une introduction bancale ou expéditive laissera une
impression négative que le meilleur développement du monde ne saura
dissiper.

Une bonne introduction occupe généralement entre une demi-page (surtout
en licence) et une page entière (principalement pour l'agrégation).
À plus d'une page et demie, elle commence à trop s'étirer : les
questions partent dans tous les sens, parce que le candidat n'arrive pas
à resserrer son étude sur une problématique unique.

** Amorce
<<amorce>>

_L'auteur de ces lignes déconseille personnellement de commencer la
copie par une amorce_.

Certains préconisent de partir d'une anecdote, d'un exemple tiré du
quotidien, d'un exemple historique etc., avant de définir les termes et
de construire la problématique. Par exemple, pour le sujet « La
guerre », on peut imaginer de partir d'une comparaison entre deux
figures historiques :
#+BEGIN_QUOTE
  Jean Jaurès est mort pour avoir refusé la guerre quand son pays la
  désirait, Jean Cavaillès pour l'avoir acceptée quand son pays y avait
  renoncé : aujourd'hui ils sont tous deux reconnus comme des « justes ».
  De ce constat paradoxal on peut tirer deux interrogations : la
  première porte sur la nature de la guerre, la seconde sur les moyens
  de son évaluation morale et politique.
#+END_QUOTE
L'ensemble de la dissertation pourra donc être vu comme la tentative
d'explication de ce simple constat : que Jaurès et Cavaillès, avec des
comportements apparemment opposés, puissent être l'objet des mêmes
éloges.

En tout état de cause, _ne partez surtout pas de l'histoire de la
philosophie_, en disant par exemple que Hobbes justifie la guerre par
l'état de nature, etc. La dissertation, dans l'introduction, doit pour
ainsi dire s'appuyer sur la fiction que la philosophie n'ait pas
préexisté à notre réflexion. La diversité des opinions philosophiques
n'est jamais un bon point de départ de dissertation : l'interrogation
sur le sexe des anges a beau avoir suscité bien des opinions contraires,
elle n'en a pas le moindre intérêt pour autant.

Mais l'amorce est hautement facultative. En cas de manque d'inspiration,
il vaut mieux en faire totalement l'économie que de la rédiger
maladroitement. _En pratique, les amorces sont presque toujours hors
sujet et reliées très artificiellement, ou pas reliées du tout, à la
problématisation_. Elles nuisent donc plus au candidat qu'elles ne lui
sont utiles. C'est pourquoi l'auteur de ces lignes recommande de ne pas
faire d'amorce et de partir directement de la définition des termes du
sujet.


** Définitions
<<definitions>>

La définition des termes du sujet est, du point de vue logique, le
véritable début de la dissertation. Une copie peut commencer
/ex abrupto/ par la définition des concepts. L'introduction est alors
sobre mais efficace.

_Ne mentionnez pas explicitement « le sujet » ou « l'intitulé »_ avec
des formules comme « Ce sujet nous propose de réfléchir sur... » ou « Le
présupposé de ce sujet est... ». Commencez directement par la définition
des termes.

La définition des termes du sujet consiste à prendre chaque terme
important de l'énoncé et à le définir conformément au sens commun. _Les
définitions ne doivent surtout pas présupposer une thèse philosophique
particulière_. Par exemple, ne définissez pas « Dieu » comme une entité
immanente à la nature (que vous pensiez ou non à Spinoza) car ce n'est
généralement pas en ce sens que l'on utilise ce terme. Vos définitions
en introduction doivent être œcuméniques et être acceptées comme des
évidences par la première personne rencontrée dans la rue. La définition
ne doit donc pas paraître arbitraire, sans quoi elle fragiliserait votre
argumentation ultérieure en la faisant dépendre d'un postulat peu
convaincant.

*** Comment élaborer une définition nécessaire et suffisante

_Une bonne définition doit être non seulement suffisante, mais aussi
nécessaire : on doit pouvoir aller du concept à la définition
/et surtout/ de la définition au concept. En termes aristotéliciens, une
bonne définition doit non seulement énoncer le genre, mais également la
différence spécifique[fn:2] ; c'est cette dernière qui fait souvent
défaut.

Voici la procédure pour parvenir à une bonne définition. 

1. _Identifier le genre_. Exemple : « la guerre est un conflit ».
2. _La définition est-elle suffisante ?_ En l'occurrence : toute guerre
   est-elle un conflit ? Chercher des contre-exemples. Si l'on n'en
   trouve pas, passer à l'étape suivante.
3. _La définition est-elle nécessaire ?_ En l'occurrence : tout conflit
   est-il une guerre ? Chercher des contre-exemples (conflits entre
   animaux, entre collègues) et se demander quels critères les
   distinguent d'une guerre. Ajouter ces critères à la définition
   jusqu'à ne plus trouver de contre-exemple.

Toute guerre est en effet un conflit (on peut donc aller du concept à la
définition), mais tout conflit n'est pas une guerre : il existe des
conflits entre collègues de travail, entre membres d'une famille, entre
mâles dominants dans un troupeau, et ces conflits ne sont pas des
guerres (on ne peut donc pas aller de la définition au concept). Il faut
donc trouver, parmi l'ensemble des conflits, ce qui distingue la guerre
en particulier. Les conflits entre animaux ne sont pas des guerres car
ils ne sont pas armés, les conflits entre personnes ne sont pas des
guerres car ils n'impliquent pas des groupes. On peut donc rajouter à
notre définition ces deux critères, et l'on obtient la définition : « la
guerre est un conflit armé entre des groupes humains »

Pour résumer, voici les conditions d'une bonne définition telles que les
a énumérées Kant :
#+BEGIN_QUOTE
  Ces mêmes opérations auxquelles il faut se livrer pour mettre à
  l'épreuve les définitions, il faut également les pratiquer pour
  élaborer celles-ci. --- À cette fin, on cherche donc 1) des
  propositions vraies 2) telles que le prédicat ne présuppose pas le
  concept de la chose 3) on en rassemblera plusieurs et on les comparera
  au concept de la chose même pour voir celle qui est adéquate 4) enfin
  on veillera à ce qu'un caractère ne se trouve pas compris dans l'autre
  ou ne lui soit pas subordonné [fn:3].
#+END_QUOTE

*** Éliminer la circularité

Il faut prendre garde à _éliminer toute circularité dans la définition_.
Par exemple, dire « la guerre est l'activité guerrière », ou « la guerre
est l'activité militaire », serait simplement transformer un nom commun
en adjectif et ne nous avancerait pas d'un pouce sur les critères qui
font qu'une activité est une guerre. Cas extrême de circularité, le Père
Étienne Noël définissait en 1647 la lumière comme « un mouvement
luminaire de rayons composés de corps lucides, c'est à dire lumineux ».

Attention, _la circularité est parfois bien cachée_. Par exemple,
définir la pensée comme « activité /mentale/ du sujet » serait s'exposer
à la question de savoir ce qu'est à son tour l'« activité mentale »...
et à la réponse spontanée : « l'activité mentale est l'activité de la
/pensée/ ». La définition est circulaire ! De même, définir l'animal en
commençant par dire qu'il est un être « biologique » ou « doué de vie »,
« animé » ou « possédant une âme » (/anima/), ce n'est que déplacer
toute la difficulté dans l'un de ces mots. On peut plutôt proposer de
définir l'animal comme « un être capable de se déplacer et de viser ses
propres fins » : on a ainsi défini le concept par des mots strictement
plus simples.


*** Explication informelle

_Après avoir énoncé la définition, vous pouvez rajouter quelques phrases
d'explication informelle_, l'illustrer par des exemples, etc. Ces
explications ne doivent surtout pas se substituer à la définition afin
de ne pas entourer le concept d'un flou impressionniste. La frontière
entre définition et explication doit être claire.

Voici quelques exemples.

Pour le sujet « Histoire et géographie » : 
#+BEGIN_quotation
L'histoire\marginpar{Définition} est la discipline qui décrit les faits
du passé selon leur ordre temporel. On parle
ainsi\marginpar{Explication}, selon les domaines, d'histoire politique,
d'histoire de l'art, d'histoire des sciences ou d'histoire des idées.

La géographie\marginpar{Définition} est la discipline qui décrit la
répartition spatiale des faits. On appelle ainsi\marginpar{Explication}
géographie physique celle qui décrit la position des montagnes et des
mers, géographie humaine celle qui décrit des phénomènes tels que la
concentration des villes ou la périurbanisation.
#+END_quotation

Pour le sujet « L'insurrection est-elle un droit ? » : 
#+BEGIN_quotation
Une insurrection\marginpar{Définition} est l'usage de la force par une
partie de la population d'un territoire contre le pouvoir qui la régit.
La prise\marginpar{Explication} de la Bastille en 1789 et les mouvements
de 2020 visant à destituer Loukachenko en Biélorussie sont ainsi des
insurrections.

Le droit\marginpar{Définitions} est l'ensemble des textes définissant ce
que le pouvoir autorise ou interdit à la population qu'il régit. Plus
strictement, « un » droit est ce dont le pouvoir garantit la possibilité
à sa population. Par exemple\marginpar{Explication}, le droit de vote
est la possibilité pour chaque citoyen de faire en sorte que l'opinion
qu'il exprime soit prise en compte lors d'une consultation.
#+END_quotation

Pour le sujet « La nature est-elle bien faite ? » : 
#+BEGIN_quotation
Par nature\marginpar{Définition}, on entend généralement l'ensemble des
choses et des processus matériels qui ne résultent pas d'une activité
humaine. On dit ainsi\marginpar{Explication} que les fleurs, la
gravitation, l'homme même en tant qu'animal relèvent de la nature.

On dit qu'une chose est bien faite\marginpar{Définition} lorsqu'elle est
conforme à une norme donnée. Un travail est bien
fait\marginpar{Explication} s'il répond aux attentes, une œuvre d'art
est bien faite si elle suscite la satisfaction attendue, une
démonstration est bien faite si elle prouve ce qu'elle entend prouver.
#+END_quotation

*** Comment définir les termes polysémiques

Souvent, un terme à définir possède plusieurs significations. Deux cas
de figure se présentent alors. 

1. Si toutes les significations sont liées les unes aux autres, allez du
   multiple à l'un, c'est-à-dire commencez par donner les différentes
   définitions, puis montrez quelle essence elles ont en commun (par
   exemple, pour le sujet « La corruption », vous pouvez chercher une
   essence commune aux emplois métaphysique, botanique et politique du
   mot).
2. Si, à l'inverse, les différentes significations sont relativement
   indépendantes les unes aux autres, distinguez clairement les
   différents emplois et éliminez ceux qui ne sont pas pertinents (par
   exemple, pour le sujet « Le corps peut-il être objet d'art ? », vous
   pouvez stipuler dès l'introduction que vous entendrez le corps
   exclusivement dans le sens de « corps humain » et non dans le sens
   métaphysique d'un individu matériel).

*** Sujets définitionnels

Il arrive que tout l'enjeu d'un sujet de dissertation soit précisément
de définir un concept, notamment quand il commence par « qu'est-ce
que » : « Qu'est-ce que le bonheur ? », « Qu'est-ce qu'agir ? »,
« Qu'est-ce qu'une chose ? », etc. _Dans un sujet définitionnel, le
concept doit recevoir /plusieurs/ définitions : la définition du sens
commun en introduction, une définition par partie et la définition
définitive en conclusion_. Ainsi, même quand la définition est l'enjeu
même de la dissertation, il faut impérativement définir le concept dès
l'introduction.


** Problématisation 
<<problematisation>>

_La problématique est la question unique que la dissertation cherche à
résoudre_. Elle doit être présentée sous la forme d'une phrase
interrogative directe.

Afin d'éviter tout risque de confusion, _l'introduction doit contenir
une seule et unique question_. Certains candidats ont tendance a
accumuler sans ordre des questions vaguement apparentées : « L'activité
théorique de l'homme peut-elle être simulée tout entière par la simple
manipulation de signes qui caractérise le calcul ? Les machines
peuvent-elles tout faire ? L'homme sera-t-il remplacé à terme par des
ordinateurs ? ». Mais cette succession de questions angoissées témoigne
parfois d'une absence de choix, d'une hésitation entre plusieurs
problématiques, et de leur simple juxtaposition. Le correcteur ne sait
pas si elles sont toutes subordonnées à la première, si elles en
précisent progressivement le sens (et dans ce cas c'est la dernière qui
doit être retenue comme problématique définitive), ou encore si elles
étudient trois aspects d'une seule et même problématique, qui quant à
elle ne serait pas mentionnée. Il faut donc en choisir une seule ; c'est
ce qui garantit l'unité de la dissertation.

_La problématique ne doit pas être la répétition pure et simple du
sujet_ : les définitions que vous avez produites vous permettent de
poser plus finement le problème. Par exemple, pour le sujet « Toute
pensée est-elle un calcul ? », on peut poser la problématique suivante :
« Peut-on, dans la pensée humaine, faire abstraction de toute
signification et n'y voir qu'une simple manipulation de signes ? ».
Entre le sujet et la problématique, on a progressé, et ce grâce aux
définitions, qui permettent de mieux comprendre où se loge véritablement
le problème.

_La problématique n'est rien d'autre que l'explicitation de ce qui, dans
le sujet tel qu'il est posé, pose un problème_ : par exemple, dans le
sujet « Toute pensée est-elle un calcul ? », l'opposition entre le
caractère apparemment sémantique de la notion de pensée et le caractère
purement syntaxique compris dans la notion de calcul. La problématique
ne doit surtout pas être conçue comme une question qui, par une suite de
glissements et d'associations d'idées, ressemble vaguement au sujet que
l'on nous a imposé sans toutefois lui être rigoureusement identique. Un
critère simple permet de s'assurer de la conformité de la problématique
au sujet : _toute réponse à la problématique doit être aussi une réponse
explicite au sujet_.

_La problématique doit être justifiée par un ou plusieurs paragraphes de
problématisation_. vous devez convaincre le lecteur qu'il y a un
problème philosophique à résoudre, sans quoi toute la dissertation qui
suit est inutile. _La problématisation doit s'appuyer uniquement sur
deux ressources : les définitions que vous avez proposées et les thèses
du sens commun_.

# Voici un exemple pour le sujet « Toute pensée est-elle un calcul ? » :

# #+BEGIN_QUOTE
#   Par pensée, on entend généralement l'ensemble de l'activité théorique
#   de l'homme. Le calcul, quant à lui, est une démarche déductive
#   reposant sur la manipulation de signes. Or, l'histoire récente montre
#   qu'un nombre croissant d'activités autrefois réservées à
#   l'intelligence humaine --- opérations mathématiques, inférences
#   logiques, prises de décisions économiques --- se voient déléguées à
#   des machines, dont le fonctionnement repose pourtant sur le seul
#   calcul. On peut donc s'interroger sur l'existence de limites à cette
#   tendance historique. L'activité théorique de l'homme peut-elle être
#   simulée tout entière par la simple manipulation de signes qui
#   caractérise le calcul ?
# #+END_QUOTE



# Évitez les problématiques factices de la forme « Dans quelle mesure... »
# ou « En quoi... ». Généralement elles ne cherchent pas à résoudre un
# problème mais à soutenir une thèse unilatérale.

Mais comment faire ? Voici la méthode pour construire une problématique
de façon rigoureuse :

1. /définition/ : je définis les principaux termes du sujet comme
   indiqué plus haut (définition nécessaire, suffisante, non circulaire
   et non arbitraire) ;

2. /substitution/ : je réécris le sujet en remplaçant chaque terme
   défini par sa définition ;

3. /tension/ : j'expose et justifie les différents aspects qui entrent
   en tension dans le sujet ainsi reformulé ;

4. /problématique/ : je condense la problématique en une question
   unique.

\noindent Appliquons cette méthode au sujet « Dieu a-t-il pu vouloir le
mal ? » :

1. /définitions/ des principaux termes :

   -  Dieu : « créateur du monde possédant toutes les perfections » ;

   -  le mal : « ce qui ne doit pas être réalisé » ;

2. /substitution/ des définitions aux termes définis dans le sujet :
   « un /créateur du monde possédant toutes les perfections/ a-t-il pu
   vouloir /ce qui ne doit pas être réalisé/ » ?

3. maintenant la /tension/ apparaît sans doute plus clairement, puisque
   l'on est tenté d'affirmer à la fois que Dieu est parfait et qu'il a
   pu vouloir un monde imparfait, ce qui semle être une imperfection de
   sa part.

\noindent On peut alors rédiger l'introduction :

#+BEGIN_quotation
  Par Dieu\marginpar{Définitions}, on entend généralement un être qui
  d'une part est créateur du monde et de l'autre possède toutes les
  perfections, c'est-à-dire toutes les qualités positives à leur degré
  ultime. C'est en ce sens que les religions monothéistes — ainsi que
  les philosophes en l'absence de mention contraire — entendent le mot
  Dieu.

  Le mal est ce qui ne doit pas être réalisé. Dire qu'un travail est mal
  fait, c'est dire qu'il n'aurait pas dû être accompli de cette façon.
  Une personne qui fait le mal est une personne qui fait ce que l'on ne
  doit pas faire. 

  Si Dieu\marginpar{Thèse commune} existe tel que nous le définissons
  ordinairement, alors dans la mesure où il possède toutes les
  perfections, il doit être infiniment bon et donc ne devrait pas
  pouvoir accomplir le mal. Dans le sens où nous l'entendons
  ordinairement, l'idée de Dieu est incompatible avec celle de
  méchanceté ou d'incompétence.

  Un rapide\marginpar{Contradiction} coup d'œil autour de nous semble
  pourtant nous présenter le mal comme l'un des principaux ingrédients
  du monde dont Dieu serait le créateur : partout la guerre,
  l'injustice, la mort. L'existence manifeste du mal semble ainsi
  contraditoire avec celle d'un Dieu possédant toutes les perfections.

  Le caractère\marginpar{Problématique} apparemment mauvais du monde
  suffit-il donc à récuser l'hypothèse de l'existence d'un dieu
  parfait ?
#+END_quotation



# **** Exemples

# Voici trois exemples de définitions et de problématiques différentes
# pour le sujet « La science » :

# #+BEGIN_QUOTE
#   1. (Définition externe, plutôt sociologique)

#   Une science se présente généralement à nous comme un ensemble
#   d'assertions qui devrait unanimement être reconnu comme vrai, et que
#   l'on suppose avoir déjà fait consensus dans une communauté de
#   spécialistes tels que les mathématiciens, les physiciens ou les
#   sociologues. Mais le simple consensus ne fait pas la vérité.
#   Existe-t-il donc à ce présumé consensus (c'est-à-dire de fait) un
#   fondement nécessaire (c'est-à-dire de droit), qui soit commun à tout
#   ce que nous appelons couramment des sciences ?

#   2. (Définition interne, plutôt épistémologique)

#   Une science est un ensemble de savoirs que l'on peut obtenir, puis
#   vérifier, selon des principes méthodologiques déterminés à l'avance.
#   Ces principes sont par exemple les axiomes et les règles de
#   démonstration du mathématicien ; ou les théories, les concepts et les
#   formules du physicien ; ou les concepts, les observations et les
#   statistiques du sociologue. La science n'est donc pas une simple
#   connaissance, c'est une connaissance par méthode. Ces principes de
#   méthode semblent pourtant eux-mêmes échapper à tout contrôle, n'étant
#   généralement pas remis en cause dans le cours normal de la science. À
#   quelles conditions l'obéissance à des principes de méthode peut-elle
#   donc valoir comme un garant de vérité ?

#   3. (Définition naïve et empirique --- parfois très efficace)

#   Nous appelons sciences un ensemble de discours tous tenus pour « vrais »
#   et pourtant de natures très variées, qui comprend notamment des
#   sciences pures comme les mathématiques et la logique, des sciences de
#   la nature comme la physique et la biologie, des sciences humaines
#   comme la psychologie et la sociologie. Certaines de ces « sciences »
#   semblent unanimement reconnues comme telles et font autorité, d'autres
#   font l'objet de débats passionnés --- la psychanalyse, l'histoire, le
#   marxisme ---, tandis que d'autres prétendus savoirs sont presque
#   unanimement classés parmi les « pseudo-sciences » --- l'astrologie,
#   l'alchimie, la physiognomonie. Existe-t-il donc des critères
#   universellement valides qui nous permettraient de déterminer avec
#   certitude si un domaine de savoir relève ou non de la science ?
# #+END_QUOTE


		
** Annonce du plan
<<annonce>>

_L'enjeu du devoir sera, dans chacune des parties, de proposer une
réponse à la problématique, donc au sujet_. La problématique doit être
équivalente au sujet, mais simplement plus développée car elle formule
explicitement la tension que le sujet ne contenait qu'implicitement.


_Sans être obligatoire, l'annonce du plan est très appréciée des
correcteurs_. Elle montre que l'étudiant sait dès le début où il va et
elle permet au correcteur de s'orienter facilement dans la copie. Rien
n'est pire pour un correcteur — donc plus nuisible au candidat — qu'une
copie dont la structure n'est pas absolument transparente.

Dans une annonce de plan, _chacune des parties annoncées doit être
formulée comme une réponse explicite à la problématique, donc au
sujet_ : le rapport ne doit surtout pas rester implicite. 

De plus, _vous ne devez pas seulement dire la thèse que vous allez
soutenir mais aussi les raisons pour laquelle vous allez la défendre_.
Ne vous contentez pas de dire : « Nous verrons d'abord que l'on peut
répondre positivement à cette question, puis que l'on peut répondre
négativement. » Il faut dire explicitement dès maintenant selon quel
critère on apportera une réponse positive et selon quel critère une
réponse négative. 

Exemple sur le sujet « Histoire et géographie » : 
#+BEGIN_quotation
Nous verrons dans un premier temps que c'est l'hétérogénéité des
dimensions spatiale et temporelle qui justifie la séparation de
l'histoire et de la géographie en deux disciplines indépendantes. Nous
montrerons ensuite que chacune des deux disciplines isole arbitrairement
l'une des dimensions des faits empiriques et qu'elles ne devraient pas
être séparées. Nous soutiendrons enfin que la distinction entre histoire
et géographie n'est pas de nature mais de degré : la géographie n'est
pas une discipline autre que l'histoire mais simplement une histoire du
temps long.
#+END_quotation


** Types de sujet
<<types>>

Il existe principalement quatre types de sujet :

1. /un seul concept/ (ou une expression) : « La substance », « L'égalité »,
   « Le génie », « Être impossible », « Voir », « Faire de nécessité vertu »,
   etc.

2. /deux concepts/ (ou, plus rarement, trois) : « Substance et
   accident », « Genèse et structure », « Corps et esprit »,
   « Convaincre et persuader », « Foi et raison », « Langue et parole »,
   « Conscience et inconscient », « Pensée et calcul », « Mathématiques
   et philosophie », « Ordre, nombre, mesure », etc.

3. /une question/ : « Toute philosophie est-elle systématique ? »,
   « Peut-on prouver l'existence de Dieu ? », « Peut-on penser l'histoire
   de l'humanité comme l'histoire d'un homme ? », etc.

4. /une citation/ : « ``Si Dieu existe, alors tout est permis'' »,
   « ``La science ne pense pas'' », « ``Pourquoi y a-t-il quelque chose
   plutôt que rien ?'' », etc.

Naturellement, différentes formulations peuvent être à peu près
équivalentes : « Pensée et calcul » et « Toute pensée est-elle un
calcul ? », ou bien « Être impossible » et « Qu'est-ce qu'être
impossible ? », etc.

*** Un seul concept

Lorsque le sujet porte sur un seul concept, les problématiques les plus
fréquentes sont :

1. un problème de /définition/ ;

2. un problème d'/existence/ ;

3. la discussion d'une /thèse/ naturelle sur ce concept.

Par exemple, sur « Être impossible », on peut s'interroger sur la
/définition/, c'est-à-dire sur ce que c'est qu'être impossible : est-ce
la même chose qu'être contradictoire ? Et si oui, contradictoire avec
quoi : les lois logiques, les lois physiques, des lois métaphysiques ?
Sur « La substance », on peut s'interroger sur l'/existence/ des
substances en elles-mêmes, et non seulement dans notre pensée. Sur « La
spéculation », on peut discuter la /thèse/ assez naturelle et répandue
selon laquelle toute spéculation est nécessairement vaine et stérile.
Mais évidemment, on peut choisir d'autres problématiques pour chacun de
ces sujets : il n'existe pas une seule bonne problématique par sujet.

*** Deux concepts

Lorsqu'un sujet comporte deux termes (ou trois, comme « Ordre, nombre,
mesure »), il existe un _piège à éviter à tout prix, qui est de traiter
le sujet concept par concept_, comme Eltsine mangeait les hamburgers
couche par couche : par exemple, de traiter, pour « Genèse et
structure », d'abord la genèse, ensuite la structure, enfin les
relations entre elles. Dans un tel traitement, seule la troisième partie
serait dans le sujet. _Il faut traiter d'entrée de jeu les relations
entre les deux notions_.

C'est en introduction, et plus précisément lors de la définition des
termes du sujet, que l'on étudie chacune des notions pour elle-même :
d'abord la genèse, ensuite la structure. Mais la problématique doit déjà
lier les deux notions et poser le problème de leur articulation.
Ensuite, chacune des parties du développement doit porter sur la nature
de cette relation.

Exemple : « Histoire et géographie ».
#+BEGIN_quotation
L'histoire\marginpar{Définitions} est la discipline qui décrit les faits
du passé selon leur ordre temporel. On parle ainsi, selon les domaines,
d'histoire politique, d'histoire de l'art, d'histoire des sciences ou
d'histoire des idées.

La géographie est la discipline qui décrit la répartition spatiale des
faits. On appelle ainsi géographie physique celle qui décrit la position
des montagnes et des mers, géographie humaine celle qui décrit des
phénomènes tels que la concentration des villes ou la périurbanisation.

Quoique\marginpar{Thèse commune} souvent regroupées dans le syntagme
scolaire d'« his\-toire-géographie », les deux disciplines sont souvent
enseignées séparément. On cherchera par exemple dans deux livres
différents une « géographie de la France » et une « histoire
de France », ce qui semble indiquer que les deux discours peuvent être
tenus indépendamment l'un de l'autre.

Pourtant\marginpar{Contradiction}, dans la mesure où ces deux sciences
traitent de faits empiriques, elles décrivent des réalités qui sont
déterminées à la fois spatialement et temporellement. On ne peut
raconter le partage de Verdun sans décrire en même temps le nouvel état
des frontières, ni raconter la bataille des Thermopyles sans faire
intervenir la topographie. Inversement, on ne peut décrire les
mouvements de population sans décrire les circonstances historiques qui
les ont causés.

Dans la\marginpar{Problématique} mesure où les faits empiriques sont à
la fois spatiaux et temporels, y a-t-il donc un sens à prétendre les
décrire selon un de ces ordres indépendamment de l'autre ?
#+END_quotation

# De même, pour traiter le sujet « Mathématiques et philosophie », on ne
# séparera pas les analyses sur les mathématiques de celles qui portent
# sur la philosophie. Il faut d'emblée étudier, par exemple, si la
# philosophie peut adopter une méthode mathématique comme dans l'/Éthique/
# de Spinoza, et si certains concepts mathématiques --- nombre
# irrationnel, nombre imaginaire, espace à $n$ dimensions etc. --- peuvent
# posséder une signification philosophique ; c'est-à-dire, en somme,
# quelle est la part de mathématiques dans la philosophie, et quelle est
# la part de philosophie dans les mathématiques.

*** Une question

Les sujets qui se présentent sous la forme d'une question sont réputés
les plus faciles, mais il faut bien prendre garde à deux pièges :

-  que la nécessité de poser la question ait bien été expliquée en
   introduction : la question ne doit pas paraître arbitraire ;

-  que la problématique ne soit pas la simple paraphrase du sujet.

*** Une citation

_Lorsque le sujet est une citation, il ne doit jamais être pris au pied
de la lettre_. Quitte à jouer sur les mots, les deux sujets suivants
appellent bel et bien des traitements distincts :

-  « Pourquoi y a-t-il quelque chose plutôt que rien ? »

-  « ``Pourquoi y a-t-il quelque chose plutôt que rien ?'' »

Dans le premier cas, le sujet est une question, tandis que dans le
second il est une citation (de Leibniz). Quand le sujet est une
question, on doit y envisager des réponses (métaphysiques,
scientifiques, phénoménologiques...), et examiner si elles sont
satisfaisantes. Quand le sujet est une citation, on doit se demander ce
qui peut nous amener à poser cette question ; par exemple, quelle est la
spécificité de l'être humain pour qu'il puisse se poser cette question
--- la question contre-factuelle par excellence ?

De même, avec le sujet « ``Tous pourris'' », il est évidemment hors de
question de développer la thèse selon laquelle tous les hommes
politiques sont corrompus, puis de voir platement que tous les hommes
politiques ne sont peut-être pas corrompus ; mais il faut s'interroger
sur l'existence même de ce slogan, sur les intérêts de ceux qui le
proclament, sur le danger qu'il représente pour la démocratie.

Une citation ne doit donc jamais être prise au pied de la lettre. Elle
doit toujours _susciter une interrogation de second degré, sur
l'existence et les conditions de possibilité du discours qu'elle
rapporte_.

* Le développement
<<developpement>>

** Les parties
<<parties>>

_Le développement est composé de deux ou trois parties_. Il vaut mieux
une bonne copie en deux parties qu'une mauvaise en trois. Rien n'est
pire qu'une troisième partie boiteuse, redondante avec la deuxième et
rajoutée à la hâte dans le seul but d'atteindre le nombre réputé
magique.

Chaque partie possède la forme suivante :

1. un court alinéa pour énoncer la _thèse de la partie_ (de deux à cinq
   lignes), et éventuellement _annoncer le plan des sous-parties_ ;
2. plusieurs alinéas : _un alinéa par sous-partie_ (voir la section
   [[sousparties]]) ;
3. pour toute partie sauf la dernière, _un alinéa de transition_ (voir
   la section [[transition]]).

On saute une ou plusieurs lignes avant et après chaque partie, mais pas
à l'intérieur d'une partie.

_Chaque partie a pour titre et pour première phrase une réponse
explicite à la problématique_. En particulier, il ne faut surtout pas
consacrer la première partie à redéfinir les termes du sujet --- ce qui
aurait dû être fait en introduction --- ou à exposer une thèse qui ne
serait que préalable à la réponse.

Il existe un certain nombre de plans récurrents, que l'on peut appeler
plan analytique, plan dialectique, plan de renversement des valeurs (par
réhabilitation ou dégradation), etc. Certains d'entre eux seront décrits
ci-dessous. Mais il faut bien se garder de vouloir appliquer un
traitement mécanique aux sujets. Appliqué à toute force à un sujet, un
plan inapproprié gâchera toute la dissertation. Ces quelques plans
récurrents sont présentés seulement à titre de suggestion, mais ce ne
sont pas les seuls plans possibles, et généralement pas les meilleurs.
Le meilleur plan sera toujours celui que vous aurez inventé
spécifiquement pour tel ou tel sujet.

*** Le plan analytique

Ce que nous appellerons ici _le plan analytique est d'une grande
efficacité car il repose sur la plus pure logique_[fn:4]. Mais il
demande une rigueur sans faille : il faut que la problématisation ait
été menée de façon absolument parfaite.

Supposons que, sur le sujet « Dieu a-t-il pu vouloir le mal ? », on ait
posé en introduction une contradiction entre les trois principes
suivants :  

- A :: Dieu est (par définition) un créateur du monde doué de toutes les
       perfections ;
- B :: le monde est (selon l'expérience manifeste) imparfait ;
- C :: un être parfait ne peut créer une œuvre imparfaite.

\noindent Ces trois principes sont manifestement contradictoires.
Si l'on veut sauver la cohérence, on doit renoncer au moins à l'un
d'entre eux[fn:5]. On en déduit trois parties possibles :

- non A ::  le monde étant imparfait (B) et un être parfait n'ayant pu
            créer une œuvre imparfaite (C), il n'existe pas de créateur
            du monde doué de toutes les perfections (non A) ;
- non B :: Dieu étant parfait (A) et n'ayant pas pu créer d'œuvre
           imparfaite (C), le monde n'est pas aussi imparfait qu'il
           semble être (non B) ;
- non C :: Dieu étant parfait (A) et le monde étant imparfait (B), il
           faut admettre qu'un être parfait peut être créateur d'une
           œuvre imparfaite (non C).
Reste à savoir quel ordre est le plus pertinent ! 


*** Le plan dialectique

Le plan dialectique est, probablement à tort, le plus populaire. À ses
élèves de l'École Normale Supérieure, Louis Althusser proclamait que
tout plan devait représenter d'abord la passion, ensuite la crucifixion,
enfin la résurrection. _Lorsque le sujet porte sur une notion d'usage
fréquent mais qui transcende l'expérience, on peut souvent adopter le
plan suivant_ :
1. cette chose /existe/​ ;
2. cette chose n'est qu'une /illusion/ ;
3. on peut faire un /usage régulateur/ de cette chose, c'est-à-dire
   postuler son existence à des fins théoriques ou pratiques, faire
   « comme si » la chose existait. Naturellement, il faut toujours
   déterminer avec précision à quel intérêt est soumis le « comme si » :
   intérêt théorique (connaître le monde), pratique (progrès moral),
   etc.

\noindent Par exemple, sur le sujet « La substance », on peut adopter le
plan dialectique suivant :
1. la substance est un /substrat/ : derrière tout phénomène doit se
   trouver une entité permanente, qui soit en même temps le support du
   discours (Aristote) ;
2. la substance est une /fiction/ : on n'a jamais d'expérience de la
   substance, mais seulement de ses manifestations (Berkeley, Hume) ;
3. la substance est une /fonction/ : la substance n'est certes jamais
   connue en elle-même, mais elle doit être pensée pour rendre possible
   une connaissance des phénomènes (Kant).

\noindent Le plan dialectique a pourtant ses inconvénients :
1. il est généralement le plan le plus attendu --- or ce qui ne surprend
   pas votre correcteur tend à l'ennuyer, surtout lorsque le même plan
   fade se voit reproduit en trente exemplaires ;
2. le désir de synthèse à tout prix engendre souvent une troisième
   partie extrêmement plate, sans saveur ni force, où l'on s'efforce de
   concilier sans combat la version amollie de thèses contradictoires.
   Souvent la deuxième partie, celle de la critique, est celle où l'on a
   pris le plus de plaisir, et dont la conciliation finale est un
   affaiblissement considérable.
Aussi convient-il parfois de sacrifier le plan dialectique à d'autres
types de plan, présentant plus de vigueur.


*** Le plan par renversement de valeurs

_Le plan par renversement de valeurs consiste à réhabiliter
progressivement une notion à forte connotation négative ou à dégrader
progressivement une notion à forte connotation positive_. Il permet
d'éviter, dans ces cas-là, les fadeurs d'un plan dialectique.

Il arrive en effet qu'un sujet de dissertation corresponde à un concept
chargé d'une forte connotation péjorative : « L'égoïsme », « L'erreur »,
« Le mauvais goût », « L'argument d'autorité », « Les causes finales »,
« L'anachronisme », etc. Un plan dialectique pourrait être ici
extrêmement fade :
1. dans une première partie, on /critique/ le concept, selon la
   conception commune (l'égoïsme est un intérêt immoral et nuisible à la
   société, l'erreur fait obstacle à la connaissance, le mauvais goût
   est une perversion du goût) ;
2. dans une deuxième partie, on /justifie/ ces concepts (l'égoïsme est
   l'intérêt dominant chez l'homme ; l'erreur est parfois fertile ; le
   mauvais goût peut revêtir un intérêt esthétique, par exemple dans le
   kitsch ou chez Warhol) ;
3. dans une troisième partie, on /concilie/ avec fadeur les deux points
   de vue précédents (l'égoïsme est parfois bon, mais il ne faut pas en
   abuser ; l'erreur est parfois fertile, mais il faut quand même faire
   attention ; le mauvais goût ne doit quand même pas être excessif).

Un plan plus puissant est alors le suivant, qui procède à une
_réhabilitation progressive du concept péjoratif_ :
1. le concept est /nuisible/ (l'égoïsme est un intérêt immoral et
   nuisible à la société, l'erreur fait obstacle à la connaissance, le
   mauvais goût est une perversion du goût) ;
2. le concept est /inévitable ou indiscernable/ (toute action a lieu sur
   fond d'égoïsme, toute connaissance repose sur une erreur, tout goût
   est mauvais) ;
3. le concept est même parfois /bénéfique/ ou souhaitable (l'égoïsme a
   des effets profitables, l'erreur fait progresser la connaissance, le
   mauvais goût fait évoluer l'histoire de l'art).

Dans ce dernier plan, il ne s'agit pas d'adopter une thèse conciliant
deux points de vue opposés, mais au contraire d'approfondir
progressivement une thèse forte, selon une véritable montée en
puissance.

Naturellement, le plan de réhabilitation est difficilement justifiable
dans certains cas : « L'esclavage », « Le terrorisme », « Le racisme ». Ici,
toute idée de réhabilitation serait assez scabreuse.

_Symétriquement au plan de réhabilitation, le plan de dégradation
consiste à dégrader un concept spontanément perçu comme positif_ : « Le
désintéressement », « La sympathie », « La vérité », « La sincérité »,
« Le bon goût », « L'égalité »... On montre alors successivement :
1. que le concept est /bénéfique/ ;
2. qu'il est /impossible ou indiscernable/ ;
3. qu'il est même parfois /nuisible/.

** Les sous-parties
<<sousparties>>

Chaque partie doit être divisée en /sous-parties/. Ici encore, le nombre
moyen est trois, mais deux ou quatre peuvent tout à fait convenir si la
matière l'exige. 

_Chaque sous-partie doit contribuer à démontrer la thèse de la partie_.
Elle se présente comme un paragraphe unique composé de trois moments :
1. la première phrase énonce clairement la _thèse de la sous-partie_ ;
2. plusieurs _phrases d'argumentation_, qui peuvent être :
   1) un raisonnement ;
   2) un exemple ;
   3) une réféfence ; 
3. une dernière phrase montrant _comment la thèse démontrée dans cette
   sous-partie contribue à démontrer la thèse de la partie_.

Ne sautez pas de lignes d'une sous-partie à l'autre : il suffit d'aller
à la ligne.

Remarquez bien que _tout raisonnement, tout exemple, toute référence
doit être précédé et suivi par l'énoncé de la thèse que vous entendez
soutenir dans cette sous-partie_ (voir un exemple de rédaction de
sous-parties dans la section [[redaction]]).

_Une copie n'est jamais jugée pour ses idées ni pour ses références mais
pour sa construction argumentative_. Aucun correcteur ne cherche dans
les copies la confirmation de ses propres convictions philosophiques. On
préfère lire des rivaux exigeants que des partisans maladroits.
N'essayez donc pas de deviner les orientations philosophiques du
correcteur, qui est souvent plus ouvert d'esprit que vous ne le croyez.
Les inspirations kantienne, heideggerienne, wittgensteinienne, quinienne
ne sont ni encouragées, ni bannies : tout dépend de la manière dont vous
argumenterez vos idées.

Pour la même raison, aucune envolée lyrique, démonstration
d'enthousiasme, abstraction délibérément confuse ne suffira à convaincre
votre lectorat. Les philosophes n'ont pas peur de l'abstraction ou de la
nouveauté : il faut simplement qu'elle soit argumentée de façon
convaincante.

On est souvent conduit, en première partie notamment, à défendre les
thèses apparemment triviales du sens commun : le mal existe, le monde
extérieur existe, etc. Il est difficile d'y trouver suffisamment de
profondeur pour remplir une partie entière. Par exemple, pour un sujet
comme « Le monde extérieur existe-t-il ? », comment peut-on consacrer
plus de deux lignes à dire que, dans la vie de tous les jours, nous
considérons l'existence du monde extérieur comme allant de soi ?
Pour remédier à ce problème, la plus-value que vous apporterez dans la
première partie ne sera pas du contenu, mais de la /structure/. Par
exemple, vous pouvez, dans chacune des trois ou quatre sous-parties de
cette première partie, mettre au jour l'une des raisons que nous avons
de croire à l'existence du monde extérieur : 
1. l'impression de résistance (le monde ne se comporte pas toujours
   comme je l'attends ou le désire),
2. l'existence d'une intersubjectivité (nos rapports avec autrui
   supposent un monde commun),
3. l'efficacité pratique de cette croyance...
Vous pouvez ainsi _reconstruire en première partie le « système
implicite » du sens commun_, le décrire comme s'il s'agissait de la
pensée d'un philosophe. La structure que vous aurez ainsi dégagée pourra
d'ailleurs vous être très utile en deuxième partie : vous pourrez alors
démonter, argument par argument, toutes les bonnes raisons que nous
avons de croire à l'existence du monde extérieur.

Si vous défendez une thèse non triviale, il vous viendra souvent à
l'esprit, au moment de l'écrire sur la copie, une objection naïve. Dans
ce cas, /écartez-la explicitement/, pour prévenir tout malentendu et
montrer que vous anticipez le sens commun et prétendez montrer quelque
chose de plus ambitieux.


*** Les raisonnements

_Toutes les ressources de la logique formelle sont directement
mobilisables pour construire un raisonnement correct_.

_Une thèse peut être démontrée /a/ /priori/ par un syllogisme_.
Supposons que, dans le cadre d'une dissertation sur le thème « Le
désintéressement », on veuille --- provisoirement ou non --- répondre
par que le désintéressement absolu n'existe pas, c'est-à-dire que toutes
nos actions sont fondamentalement intéressées. Une preuve /a priori/
pourrait être la suivante :
#+BEGIN_QUOTE
  L'homme est un être vivant ; or, un être vivant ne peut être poussé à
  agir d'une manière déterminée que s'il y est poussé par un intérêt ;
  par conséquent, l'homme est principalement motivé par des intérêts, et
  non par des valeurs morales.
#+END_QUOTE
Matériellement, les prémisses de cet argument sont certes contestables :
il faut avoir préalablement montré que l'intérêt et la valeur sont
mutuellement exclusifs, et que l'homme est un être vivant exactement au
même titre que les animaux ; mais l'essentiel, de notre point de vue
actuel, réside dans le caractère /a priori/ de l'argument. Celui-ci est
un syllogisme formellement valide [fn:6].

Une façon de récuser une thèse est de _montrer une faille dans le
raisonnement adverse_. Supposons quelqu'un soutienne la thèse « il n'y a
pas d'action désintéressée » en commettant, comme il arrive souvent, une
erreur de quantificateur (« il n'existe pas d'action désintéressée,
puisque nous voyons sans cesse les hommes autour de nous agir selon leur
intérêt ») ou une erreur de modalisateur (« il n'existe pas d'action
désintéressée, puisqu'il est possible que tout homme ne soit mû que par
son intérêt personnel »). Dans ce cas, montrez explicitement quelle est
la faille, et vous aurez réfuté la démonstration (reste à démontrer la
thèse inverse).

Une deuxième façon de récuser une thèse est _d'attaquer les prémisses ou
les présupposés du raisonnement adverse_. Supposons que quelqu'un nie
l'existence d'actions désintéressées en s'appuyant sur un syllogisme
valide : « L'homme est un être vivant ; or, un être vivant ne peut être
poussé à agir d'une manière déterminée que s'il y est poussé par un
intérêt ; par conséquent, l'homme est principalement motivé par des
intérêts, et non par des valeurs morales ». Vous pouvez réfuter cette
argumentation en rejetant l'une des prémisses -- par exemple en disant
que l'homme ne se réduit précisément pas à son animalité (ou du moins
/pas nécessairement/, ce qui suffit à invalider la conclusion du
syllogisme).

Une troisième façon de récuser une thèse est de _critiquer les
définitions des termes_. Si quelqu'un soutient qu'il n'y a pas d'action
désintéressée, vous pouvez critiquer cette thèse en disant qu'elle
confond différentes sortes d'intérêt, qu'il faut en réalité distinguer :
par exemple l'intérêt personnel, l'intérêt collectif, l'intérêt
rationnel...


*** Les exemples

_Utiliser des exemples, c'est montrer que vos thèses se vérifient à même
les choses et qu'elles ne sont pas séparées du réel qu'elles prétendent
décrire_. Les exemples jouent donc un rôle crucial dans une
dissertation. Dans une dissertation de philosophie politique, citez des
événements historiques appartenant à des époques variées ; dans une
dissertation d'esthétique, citez des œuvres d'art relevant d'époques et
de genres variés ; dans une dissertation d'épistémologie, donnez des
exemples scientifiques ; dans une dissertation de morale, de philosophie
du langage etc., donnez toujours des exemples concrets.

La valeur argumentative d'un exemple dépend du type de thèses pour
lequel il est mobilisé. On peut vouloir démontrer ou réfuter une thèse
universelle, c'est-à-dire de la forme « tous les... sont... » ; on peut
aussi vouloir démontrer une thèse existentielle, c'est-à-dire de la
forme « certains... sont... ».

_Pour /démontrer/ une thèse /existentielle/, il suffit d'un exemple
quelconque_. Si vous voulez démontrer la thèse « il existe des guerres
justes », il suffit de prendre un exemple, en justifiant qu'il s'agit
bien d'une guerre et qu'elle est bien juste. Si vous voulez démontrer la
thèse « il est possible d'apprendre à être artiste », il suffit de
montrer que les écoles d'art enseignent à être artiste.

_Pour /réfuter/ une thèse /universelle/, il suffit également d'un
contre-exemple quelconque_. Pour réfuter la thèse « toute action est
intéressée », inutile de montrer que /toute/ action est désintéressée !
Il suffit d'exhiber un seul cas de bonne action dont on puisse montrer
qu'il s'agit bien d'une action désintéressée.

Attention toutefois : _un exemple quelconque ne suffit pas pour
/démontrer/ une thèse /universelle/, /réfuter/ une thèse
/existentielle/, démontrer une nécessité ou réfuter une possibilité_.
Il ne serait par exemple pas convaincant de dire : « Comme le montre
l'exemple de Staline, tous les hommes sont mauvais ». La preuve n'est
pas convaincante, car de ce qu'il ait existé /certains/ hommes mauvais,
elle conclut que /tous/ les hommes sont mauvais. En termes logiques, le
sophisme repose sur une confusion entre quantificateurs ou entre
modalisateurs. La généralisation est abusive.

_Le seul type d'exemples qui permette de /démontrer une thèse
universelle/ /réfuter une thèse existentielle/, démontrer une nécessité
ou réfuter une possibilité est l'exemple-limite_, c'est-à-dire un
exemple qui semble tellement /invalider/ notre thèse que si l'on arrive
à montrer que /même lui/ la vérifie, elle celle-ci se vérifie
/a fortiori/ dans tous les autres cas. Si vous arrivez à montrer que
même les actions apparemment les plus désintéressées de Gandhi étaient
en réalité fondamentalement intéressées, alors votre thèse vaudra
/a fortiori/ non seulement pour Staline, mais pour tous les autres êtres
humains. Vous fournirez ainsi, selon les termes de Gilles Gaston
Granger, « une vérification de cette hypothèse sur des cas exemplaires,
délibérément choisis comme particulièrement défavorables à sa
démonstration [fn:7] ».

Résumons donc les types d'exemples qui peuvent être utilisés dans les
différents cas de figure :
|---+-----------+----------------------+--------------------|
|   |           | Thèse d'universalité | Thèse d'existence  |
|   |           | ou de nécessité      | ou de possibilité  |
| / | <         | <                    | <>                 |
|---+-----------+----------------------+--------------------|
|   | Démontrer | exemple-limite       | exemple quelconque |
|---+-----------+----------------------+--------------------|
|   | Réfuter   | exemple quelconque   | exemple-limite     |
|---+-----------+----------------------+--------------------|





*** Les références 

_La première phrase d'un alinéa, où l'on annonce la thèse à venir, et la
dernière, où l'on résume la thèse examinée, ne doivent contenir aucun
nom de philosophe_. Les références ne doivent apparaître qu'à
l'intérieur des sous-parties comme une contribution à l'argumentation.
Elles ne doivent pas être citées pour elles-mêmes, sous peine de tomber
dans la doxographie.

De plus, _chaque référence doit être soigneusement développée et
analysée_. Une phrase ne suffit pas. Développer une référence permet
d'éviter l'érudition allusive. Un philosophe n'est ni un totem, ni un
tabou. Une sottise, même énoncée par Kant, reste une sottise [fn:8] : un
grand nom n'est jamais une autorité. Aussi toute assertion, même reprise
de Kant, doit-elle être fondée au même titre que si c'était la vôtre.
Une thèse n'est en effet jamais isolée dans l'œuvre d'un philosophe : en
ceci, elle est toujours plus qu'une simple citation. Elle s'inscrit dans
un système, ou plus modestement dans un ensemble de raisons, et c'est
sur lui qu'il faut la fonder.

Pour cette raison, une citation, à elle seule, est rarement éclairante.
Elle doit être décortiquée, expliquée, justifiée. Une copie sans
citation, dans laquelle toutes les thèses sont justifiées les unes par
les autres, est largement préférable à un agrégat de citations supposées
transparentes et autosuffisantes. Rien ne saurait donc être plus
nuisible à une dissertation philosophique que le /Dictionnaire de
citations/, catalogue d'aphorismes certes rhétoriquement habiles, mais
dont la profondeur n'est souvent qu'apparente, et la systématicité
toujours absente.

Un philosophe doit toujours être cité avec la plus grande précision
possible. Il ne suffit pas de dire que Kant a affirmé quelque part
l'existence de connaissances synthétiques /a priori/ : il faut au moins
renvoyer à la /Critique de la raison pure/, voire plus précisément à son
Introduction.

On peut mentionner quelques citations si on a le bonheur de les
connaître par cœur. Mais si l'on a peu de mémoire, un résumé fidèle des
thèses d'un philosophe n'a pas moins de valeur. En outre, les citations
ont souvent un effet pervers : pour compenser l'effort qu'a nécessité
leur apprentissage, on tend à les mobiliser à tort et à travers ou à en
faire un usage purement décoratif. L'essentiel est, à l'inverse, de
reconstruire explicitement le raisonnement qui fonde l'auteur cité à
énoncer cette formule.

** Transitions
<<transition>>

_Les transitions ne sont pas une simple exigence rhétorique, mais
obéissent à une véritable nécessité argumentative : la continuité entre
les parties_. Une transition procède typiquement en trois moments :

1. /résumer/ en une seule phrase la thèse que l'on vient d'exposer ;

2. montrer de manière détaillée, et surtout pas de manière symbolique ou
   allusive, ce qui /manque/ à cette thèse ;

3. soumettre l'/ébauche/ d'une solution, telle qu'elle sera développée
   dans la partie ou la sous-partie suivante.

Chacun de ces trois moments est crucial, mais c'est souvent le second
qui fait défaut : si l'on change de point de vue sans avoir vraiment
montré pourquoi il était /absolument nécessaire/ (et non simplement
possible) de le faire, si l'on ne montre pas clairement dans la
transition pourquoi le point de vue adopté jusqu'ici est insatisfaisant
et doit être abandonné, le lecteur n'a strictement aucune raison de lire
la partie suivante.

Par exemple, supposons que nous ayons adopté le plan suivant pour le
sujet « La guerre » :

1. la guerre est un /déchaînement de violence/ ;

2. la guerre est une violence, mais dirigée par l'intellect : une
   /violence rationnelle/ ;

3. la pertinence de la guerre dépend des valeurs qui la motivent : sous
   certaines conditions, elle peut devenir une /violence raisonnable/.

\noindent La transition de la première à la deuxième partie peut être
l'alinéa suivant :

#+BEGIN_QUOTE
  Nous avons vu que la guerre pouvait se présenter au premier abord
  comme un déchaînement de violence, s'inscrivant dans la continuité de
  la rivalité entre les individus pour satisfaire leurs besoins naturels
  (boire, manger, respirer...). Mais ce serait méconnaître trois
  distinctions essentielles. D'abord, les belligérants ne sont pas des
  individus, mais des entités plus abstraites et plus larges, à savoir
  des États. Ensuite, les motivations d'une guerre sont rarement
  réductibles aux conditions de la satisfaction des besoins naturels :
  on entre en guerre pour s'assurer une position économique privilégiée,
  pour acquérir des terres riches en minerais, pour faire coïncider les
  frontiètres politiques de l'« État » avec les frontières culturelles de
  la « nation », pour laver l'humiliation d'une guerre passée, pour
  répandre la liberté révolutionnaire dans le monde entier, pour
  réaliser le communisme international, pour agrandir son « espace
  vital », pour recouvrer la terre de ses ancêtres, etc. : rien n'animal
  dans toutes ces motivations. Enfin, les moyens d'action sont de plus
  en plus « raffinés » : loin de la pierre que l'on jette à autrui, on
  fait de plus en plus appel aux dernières avancées scientifiques (armes
  à feu, bombes atomiques, armes chimiques ou bactériologiques). Loin
  d'être un pur et simple déchaînement de violence, la guerre se
  caractérise donc par un appel constant à l'intelligence. Ne faut-il
  pas, dès lors, considérer que la rationalité est aussi essentielle à
  la guerre que la violence ?
#+END_QUOTE

Lorsque l'on adopte un plan dialectique, l'une des transitions doit être
plus soignée encore que toutes les autres : celle qui conclut la
deuxième partie et annonce la troisième. Ici, plus de quinze lignes sont
rarement un luxe. Il faut prendre le temps de bien montrer toute la
tension à laquelle on est parvenu, dans sa radicalité. Plus la
contradiction est radicale, plus la résolution est attendue avec
impatience : il faut savoir susciter l'intérêt du correcteur !

* La conclusion
<<conclusion>>

_Le rôle de la conclusion est simple : elle doit répondre clairement à
la problématique_. Elle doit notamment contenir une phrase que le
correcteur puisse retenir comme votre réponse au sujet. Elle doit être
rédigée avec soin : certains correcteurs la lisent même juste après
l'introduction afin de vérifier que le candidat sait où il va !

Il faut _fuir comme la peste les conclusions paresseuses_, comme « on a
vu qu'il existait beaucoup de réponses différentes à cette question » ou
« on a vu que cette notion est complexe et comporte de nombreux
aspects ». On peut certes conclure sur une impossibilité de trancher,
mais elle doit être argumentée, et non s'appuyer sur la seule diversité
des opinions. La diversité des opinions n'est plus un bon point
d'arrivée de dissertation qu'un bon point de départ.

_La conclusion doit être une synthèse de la dissertation et non une
table des matières_. À cette fin, il suffit de remplacer toutes les
déterminations temporelles --- « d'abord », « ensuite », « enfin » etc.)
--- par des liens logiques : « si l'on conçoit... alors... », « même
s'il peut sembler que... », « dans la mesure où... », etc.

_La conclusion ne doit contenir /aucun nom de philosophe/_. C'est vous
qui parlez en votre nom. Ne dites donc jamais : « en adoptant un point
de vue heideggerien, on peut dire que... ». Si vous avez adopté le point
de vue de Heidegger en citant cet auteur à la fin de votre dernière
partie, il est temps maintenant de voler de vos propres ailes ; vous
n'avez plus besoin de Heidegger pour porter les idées que vous vous êtes
appropriées.

# ** L'ouverture du sujet

# Si vous êtes partis d'une amorce, la reprendre en conclusion pour
# l'éclairer d'un jour nouveau peut être instructif ; bien manipulé, ce
# procédé confère à la dissertation une efficacité qui n'est pas seulement
# rhétorique, mais également spéculative : il montre que vous saviez dès
# le départ où vous alliez, et que le cheminement n'a pas été improvisé
# ligne après ligne.

# Par exemple, sur le sujet « La guerre », on peut faire écho en conclusion
# à l'amorce qui comparait Jaurès et Cavaillès :

# #+BEGIN_QUOTE
#   Si le pacifiste Jaurès et le résistant Cavaillès peuvent être tous
#   deux considérés comme des justes, c'est que l'opposition formelle de
#   la guerre et de la paix n'est pas tenable, sans quoi Jaurès serait
#   lâche ou Cavaillès militariste. Il nous faut donc distinguer deux
#   sortes de guerres, correspondant à deux sortes de paix. Si Jaurès
#   était pacifiste, ce n'était pas par simple refus de la guerre (la paix
#   comme absence de guerre, ou /paix négative/), mais au nom d'une /paix
#   positive/ conçue comme entente entre les peuples. Si Cavaillès
#   s'engagea dans la Résistance après l'Armistice, ce n'était pas par
#   refus belliciste de l'état de paix, mais au nom d'une paix positive
#   --- son avènement dût-il passer par la guerre --- et contre la paix
#   négative s'accommodant de l'Occupation et des crimes dont elle fut le
#   théâtre. En distinguant ces deux sortes de paix, on peut concevoir la
#   proximité de ces deux personnes, qui est d'avoir subordonné le
#   problème de la /valeur/ de la guerre prise absolument à celui de sa
#   /pertinence/ dans une situation historique précise. Si l'on peut
#   parler de « justes », c'est parce qu'ils ne pensèrent pas en opposant
#   simplement guerre et paix, mais guerre injuste et paix juste pour
#   Jaurès, guerre juste et paix injuste pour Cavaillès.
# #+END_QUOTE

_L'auteur de ces lignes déconseille fortement de terminer la conclusion
par une ouverture du sujet_. Ce procédé, généralement mal maîtrisé,
a des effets catastrophiques pour les candidats : soit ils abordent des
problèmes qui n'ont aucun rapport avec le sujet (« car, après tout,
qu'est-ce que la vérité ?... »), soit ils posent bien trop tard des
problèmes qui auraient dû être traités (« une nouvelle question se pose,
qui serait celle des valeurs au nom desquelles on mène une guerre »). Il
vaut mieux éviter ce procédé et terminer directement par la réponse à la
question : ici encore, la sobriété est parfois gage d'efficacité.

# * Comment les correcteurs lisent les copies

# Savoir sur quels critères vous êtes évalué vous permettra de rédiger des
# copies satisfaisant le mieux possibles les attentes du correcteur.

# ** Ordre de lecture

# Voici un exemple de lecture de copie. Le correcteur lit d'abord
# l'introduction et la conclusion. À ce stade, il a souvent une idée de la
# note à quatre points près. C'est comme s'il raisonnait par grandes
# cases :

# -  une case A pour les très bonnes copies, de 14 à 20 ;

# -  une case B pour les copies correctes, de 10 à 14 ;

# -  une case C pour les copies insatisfaisantes, de 6 à 10 ;

# -  une case D pour les copies inachevées ou bâclées, en dessous de 6.

# Ayant ainsi provisoirement identifié le profil de la copie, le
# correcteur lit le développement, pour voir si les thèses sont
# correctement argumentées : il juge la qualité de la démonstration, la
# pertinence des exemples et des références philosophiques. Généralement,
# le développement ne fera pas changer la copie de case --- du moins, pas
# dans un sens favorable au candidat : une copie qui commence et qui finit
# mal contient rarement un développement éblouissant. Le développement
# permet surtout au correcteur de savoir où positionner la copie dans la
# case qui lui correspond (A$+$, A$-$, B$+$, B$-$, ...) ; il permet donc
# au candidat de gagner jusqu'à quatre points.

# ** Critères d'évaluation

# Voici, dans l'ordre, les questions que le correcteur peut se poser.

# 1. Je lis l'introduction.

#    -  Les principaux termes du sujet ont-ils été définis, au moins de
#       façon provisoire ?

#    -  Le sujet est-il bien problématisé, en partant de la construction
#       d'une véritable tension ?

#    -  Chacune des parties annoncées répond-elle à la problématique ?

#    L'introduction permet déjà de savoir si le candidat s'est approprié
#    le sujet pour le penser de façon personnelle.

# 2. Je lis la conclusion.

#    -  La copie est-elle achevée ?

#    -  La conclusion répond-elle clairement à la question posée dans
#       l'introduction ?

#    -  La conclusion est-elle intéressante, c'est-à-dire non triviale ?

# 3. Je lis le développement.

#    -  La réflexion de chaque partie est-elle structurée en sous-parties,
#       dont chacune contient une thèse ?

#    -  Chaque thèse est-elle soutenue par une démonstration, ou par un
#       exemple suffisamment analysé ?

#    -  Le candidat mentionne-t-il les doctrines philosophiques de manière
#       détaillée, en évitant l'avalanche de références évoquées de
#       manière allusive ?

#    -  Les transitions sont-elles pertinentes ?

* Exemple de plan détaillé : La nature est-elle bien faite ? 
<<plandetaille>>

*[Introduction]*

Par nature\marginpar{Définitions}, on entend généralement l'ensemble des
choses et des processus matériels qui ne résultent pas d'une activité
humaine ; on dit ainsi que les fleurs, la gravitation, l'homme même en
tant qu'animal relèvent de la nature.

On dit qu'une chose est bien faite lorsqu'elle est conforme à une norme
donnée : un travail est bien fait s'il répond aux attentes, une œuvre
d'art est bien faite si elle suscite la satisfaction attendue, une
démonstration est bien faite si elle prouve ce qu'elle entend prouver.

On dit\marginpar{Thèse commune} souvent, dans la langue de tous les
jours, que « la nature est bien faite » — par exemple lorsque l'on
observe que les oiseaux sont dotés d'os creux qui permettent le vol, que
le chou romanesco possède une forme fractale, que les végétaux
consomment le carbone que les animaux rejettent et produisent en retour
l'oxygène qu'ils respirent.

Mais dire\marginpar{Contradiction} qu'une chose est bien faite, c'est la
considérer comme répondant à une norme donnée, donc comme
intentionnelle, ce qui semble précisément exclure la nature, qui se
définit par son caractère non intentionnel. Quand on dit que la nature
est bien faite, on affirme en même temps qu'en tant que nature elle
n'est pas le résultat d'une intention, et qu'en tant que bien faite tout
semble indiquer qu'elle est le résultat d'une intention. Dire que la
nature est bien faite semble donc une contradiction dans les termes :
rien de ce qui est « bien fait » ne peut être naturel.

L'expression\marginpar{Problématique} ne pouvant être prise au pied de
la lettre, y a-t-il un sens légitime à affirmer que la nature est bien
faite ou est-ce une pure et simple illusion ?

Pour\marginpar{Plan} répondre à cette question, nous verrons dans un
premier temps que la nature est dite bien faite quand elle est adaptée à
certaines fins. Ensuite, nous montrerons que cette affirmation est
illégitime d'un point de vue théorique car ces fins sont en réalité
projetées par l'homme. Enfin, nous soutiendrons que dans la mesure où la
nature relève de la responsabilité humaine, c'est à l'homme qu'il
appartient de faire en sorte qu'elle soit bien faite.

\bigskip

*I. Dire que la nature est bien faite, c'est observer son adaptation à
certaines fins*


\medskip

A) _La nature est parfois adaptée à des fins pratiques_
- haut degré de sophistication dans les objets naturels : camouflage,
  toiles d'araignée...
- une inspiration pour la technique humaine
- ces choses sont bien faites quand elles sont bien adaptées à leurs
  fins
  + toile d'araignée : souplesse et résistance
  + os creux des oiseaux pour voler
- => les choses ne sont pas bien faites dans l'absolu, mais seulement
  par rapport à des fins déterminées

\medskip
	
B) _La nature est parfois adaptée à des fins esthétiques_ 
- beaux objets dans la nature : papillons, fleurs, paysages...
- parfois cela répond à une utilité, par exemple la sélection sexuelle
- mais pas toujours : paysages de montagne chez Rousseau (/Confessions/​)
- alors on juge que la nature est bien faite /pour nous/ : plaisir
  esthétique, comme si la nature était faite pour nous plaire
- et pourtant on sait bien que ce n'est pas le cas ! la finalité est
  subjective, pas objective 

\medskip

C) _Transition_
- distinction apparente entre deux finalités
  1. finalité objective : les choses de la nature obéissent à une
     fonction effective (alimentation, reproduction...)
  2. finalité subjective : les choses de la nature obéissent à une fin
     que nous projetons arbitrairement sur elle
- mais les deux cas sont-ils vraiment différents ?
  + difficulté de décider dans les cas particuliers, par exemple l'écume
    des bateaux et les rainures du melon selon Bernardin de Saint-Pierre
  + rien n'atteste qu'il existe des fins dans la nature
  + cela semble même contradictoire avec sa définition (absence
    d'activité humaine, qui est intentionnelle)
- sommes-nous donc fondés à prêter des fins à la nature ? 

\bigskip


*II. Ce n'est pas en soi que la nature est bien faite, mais seulement
par rapport à des fins projetées par l'homme*

\medskip

A) _L'idée de finalité naturelle n'a pas de fondement épistémologique_
- on n'observe aucune fin dans la nature : l'araignée tisse sa toile et
  c'est nous qui inversons l'ordre des faits
- différence avec l'activité humaine, où le langage garantit
  l'intentionnalité
  + la représentation de l'effet précède la cause et peut être exprimée
    avant
  + par exemple le plan de construction
- le progrès scientifique tend à éliminer les finalités naturelles 
  + Darwin : renversement de la finalité en causalité
  + reproduction avec variations (phénomène causal aléatoire)
  + certaines variations sont mieux adaptées au milieu et favorisent la
    reproduction (phénomène causal de sélection naturelle)
- => pas besoin de finalité : la causalité suffit

\medskip

B) _L'idée de finalité naturelle est métaphysiquement suspecte_ 
- par qui la nature serait-elle bien faite ?
  + pas l'homme, puisque la nature n'est pas le résultat de l'activité
    humaine
  + alors seulement son créateur, c'est-à-dire Dieu
  + => dire que la nature est bien faite, c'est présupposer une création
    et une intention divines (preuves de l'existence de Dieu par
    Bernardin de Saint-Pierre)

\medskip

C) _Transition_
- l'affirmation apparemment innocente selon laquelle la nature est bien
  faite cache de lourdes hypothèses métaphysiques
  + mais généralement ce n'est pas ce que l'on veut dire !
  + cela veut-il dire que l'expression est totalement dénuée de sens, ou
    peut-on la justifier ?
  + pour cela, il faudrait pouvoir justifier le statut des fins :
    garantir qu'elles ne sont pas arbitraires

\bigskip


*III. C'est à l'homme qu'il revient de faire en sorte que la nature soit
bien faite*

\medskip

A) _La nature n'a pas initialement de fins mais elle est investie de fins_ 
- la nature ne pourrait être dite bien faite que si l'on connaissait ses
  fins
  + en soi, la nature n'est pas bien ou mal faite
  + elle est telle qu'elle est
- les fins que l'on attribue à la nature sont arbitraires car ce sont
  celles dont les investissent ses habitants, à commencer par le plus
  puissant d'entre eux : l'être humain
- mais ces fins arbitraires n'en existent pas moins ! on peut donc
  prendre pour critère l'adéquation entre l'état de la nature et les
  intérêts de ses habitants

\medskip

B) _Redéfinir la nature en tenant compte de la responsabilité humaine_
- la définition de la nature doit être précisée
  + elle ne résulte pas de l'activité humaine, mais aujourd'hui elle en
    dépend : anthropocène, changement climatique, disparition d'espèces,
    pollution...
  + l'homme n'a pas créé la nature mais il la transforme donc il en est
    responsable : l'état de la nature dépend de son action et il peut en
    être blâmé  
  + il est donc largement responsable de son état présent et futur

\medskip

C) _Les fins sont simplement régulatrices_
- l'homme n'a pas de mission et la nature n'a pas de destin certain
- mais on peut « faire comme si » la nature avait pour fin son
  adaptation à ses habitants
- on fait alors, en termes kantiens, un usage « régulateur » plutôt que
  « constitutif » de la notion de finalité

\bigskip


*[Conclusion]*

Si l'on\marginpar{Synthèse conceptuelle} prend en un sens théorique
l'affirmation selon laquelle la nature est bien faite, celle-ci est
dénuée de sens ou indécidable : elle consiste à examiner comme soumise à
une finalité un objet qui par définition en est dénué, ou à lui prêter
des fins arbitraires.

L'histoire a pourtant transformé cette question théorique en question
morale et politique : la nature ayant vu l'émergence d'une finalité
humaine dotée de moyens techniques susceptibles d'influer son cours, son
adéquation à des fins relève aujourd'hui non plus seulement de la
contemplation, mais avant tout de l'action et de la responsabilité
humaine. 

L'homme\marginpar{Réponse claire} ne peut donc pas savoir si la nature
est bien faite, mais doit agir pour qu'elle le devienne.

* Exemple de dissertation rédigée : La nature est-elle bien faite ? 
<<redaction>>

Par nature\marginpar{Définitions}, on entend généralement l'ensemble des
choses et des processus matériels qui ne résultent pas d'une activité
humaine ; on dit ainsi que les fleurs, la gravitation, l'homme même en
tant qu'animal relèvent de la nature.

On dit qu'une chose est bien faite lorsqu'elle est conforme à une norme
donnée : un travail est bien fait s'il répond aux attentes, une œuvre
d'art est bien faite si elle suscite la satisfaction attendue, une
démonstration est bien faite si elle prouve ce qu'elle entend prouver.

On dit\marginpar{Thèse commune} souvent, dans la langue de
tous les jours, que « la nature est bien faite » — par exemple lorsque
l'on observe que les oiseaux sont dotés d'os creux qui permettent le
vol, que le chou romanesco possède une forme fractale, que les végétaux
consomment le carbone que les animaux rejettent et produisent en retour
l'oxygène qu'ils respirent.

Mais dire\marginpar{Contradiction} qu'une chose est bien faite, c'est la
considérer comme répondant à une norme donnée, donc comme
intentionnelle, ce qui semble précisément exclure la nature, qui se
définit par son caractère non intentionnel. Quand on dit que la nature
est bien faite, on affirme en même temps qu'en tant que nature elle
n'est pas le résultat d'une intention, et qu'en tant que bien faite tout
semble indiquer qu'elle est le résultat d'une intention. Dire que la
nature est bien faite semble donc une contradiction dans les termes :
rien de ce qui est « bien fait » ne peut être naturel.

L'expression\marginpar{Problématique} ne pouvant être prise au pied de
la lettre, y a-t-il un sens légitime à affirmer que la nature est bien
faite ou est-ce une pure et simple illusion ?

Pour\marginpar{Plan} répondre à cette question, nous verrons dans un
premier temps que la nature est dite bien faite quand elle est adaptée à
certaines fins. Ensuite, nous montrerons que cette affirmation est
illégitime d'un point de vue théorique car ces fins sont en réalité
projetées par l'homme. Enfin, nous soutiendrons que dans la mesure où la
nature relève de la responsabilité humaine, c'est à l'homme qu'il
appartient de faire en sorte qu'elle soit bien faite.

#+BEGIN_CENTER
*

[À l'écrit : saut de lignes. À l'oral : silence de plusieurs secondes.]
#+END_CENTER

Au sens le plus évident\marginpar{Thèse et plan}, dire que la
nature est bien faite, c'est observer son adaptation à certaines fins.
Tel est le cas aussi bien lorsque nous jugeons la nature /utile/ que
quand nous la jugeons /belle/​.

On dit en effet\marginpar{Thèse de s.-p.} que la nature est bien faite
quand elle répond à des fins pratiques : la nature est alors /utile/​ à
elle-même. On observe souvent le haut degré de sophistication de
certains objets naturels : les techniques\marginpar{Exemples} de
camouflage de certains animaux, la complexité des toiles d'araignée
etc., au point que ces objets sont même parfois une source d'inspiration
pour la technique humaine. Si nous jugeons ces productions naturelles
« bien faites », c'est parce qu'elles sont bien adaptées à leurs fins :
le camouflage permet efficacement à l'animal d'échapper à ses
prédateurs, ce qui est son objectif afin de pouvoir se maintenir en vie
et perpétuer son espèce ; la toile d'araignée possède des propriétés de
souplesse, de résistance et de discrétion qui lui permettent d'attraper
facilement des proies et de se nourrir ; les os creux des oiseaux leur
offrent la légèreté qui permet le vol tout en assurant la rigidité de
leur structure. On voit\marginpar{Conclusion de s.-p.} ainsi que
la nature n'est pas jugée bien faite de façon absolue, mais seulement
par rapport à des fins déterminées.

Il pourrait\marginpar{Thèse de s.-p.} sembler que l'on juge parfois la
nature bien faite sans la rapporter à des fins pratiques. C'est le cas
lorsque l'on trouve la nature /belle/​ : les couleurs\marginpar{Exemples}
chamarrées des papillons, les fleurs et leur parfum, les paysages...
Mettons évidemment de côté les cas où la beauté réponde à une certaine
utilité, par exemple la sélection sexuelle pour la queue du paon. Il
semble évident qu'un paysage de montagne, comme ceux qu'admire
Jean-Jacques Rousseau dans les /Confessions/​, ne réponde à aucune
utilité pratique. Juger beau ce paysage et dire à son sujet que la
nature est bien faite, ce n'en est pas moins estimer qu'elle est bien
faite /pour nous/​ : le plaisir esthétique qu'elle nous procure nous
donne l'impression qu'elle est faite pour nous plaire, quand bien même
nous savons que ce n'est pas le cas. Même dans le plaisir
esthétique\marginpar{Conclusion de s.-p.}, nous jugeons que la nature est bien
faite en la rapportant à certaines fins.

Il semble donc\marginpar{Conclusion de partie} que l'on puisse
distinguer deux types de finalité par rapport auxquelles nous jugeons la
nature bien faite. La première est une finalité /objective/​ : nous la
constatons lorsque les choses de la nature obéissent à une fonction
effective telle que l'alimentation ou la reproduction. La seconde est
une finalité /subjective/​ : les choses de la nature obéissent à une fin
que nous projetons arbitrairement sur elle. Mais
avons-nous\marginpar{Transition} vraiment les moyens de discerner les
deux cas ? Il est parfois difficile de décider dans les cas
particuliers. Bernardin de Saint-Pierre a cru voir dans l'écume et les
rainures du melon les traces d'une finalité objective, l'écume servant à
prévenir les bateaux de la présence d'un rocher et les rainures du melon
le prédestinant au partage familial. Or non seulement rien n'atteste
qu'il existe des fins dans la nature, mais cela semble même
contradictoire avec sa définition : l'absence d'activité humaine semble
exclure toute intentionnalité réfléchie. Sommes-nous donc fondés à
prêter des fins à la nature et donc à juger que la nature est
objectivement bien faite, ou n'est-ce toujours là qu'une projection
illégitime ?

#+BEGIN_CENTER
*

[À l'écrit : saut de lignes. À l'oral : silence de plusieurs secondes.]
#+END_CENTER

Non seulement\marginpar{Thèse et plan} la nature n'est bien faite que
par rapport à des fins, mais ces fins elles-mêmes sont librement
projetées sur elle par l'être humain. Nous verrons ainsi que non
seulement l'idée de finalité naturelle n'a pas de fondement
/épistémologique/​, mais qu'elle est /métaphysiquement/​ suspecte.

L'idée de finalité naturelle n'a d'abord aucun fondement
/épistémologique/​\marginpar{Thèse de s.-p.}. À proprement parler, on n'observe
jamais aucune fin dans la nature. Tout ce que nous
voyons\marginpar{Exemples}, c'est une araignée qui tisse sa toile, puis
des insectes qui y sont pris avant d'être mangés par l'araignée. De quel
droit affirme-t-on que l'araignée a tissé sa toile /pour/ attraper des
proies ? C'est nous qui inversons l'ordre des faits en supposant que la
représentation de la fin (la capture) a précédé la cause (le tissage).
N'ayant pas eu avec l'araignée la discussion préalable que nous pouvons
par exemple avoir avec un architecte, nous ne pouvons affirmer que telle
était la finalité de son action. Le progrès scientifique tend même à
éliminer les finalités naturelles pour les remplacer par la simple
causalité. Darwin\marginpar{Référence} a ainsi montré que même les cas
apparemment les plus flagrants de finalité pouvaient être réduits à un
mécanisme causal. Les êtres vivants ne se reproduisent pas à l'identique
mais avec des variations aléatoires, selon un mécanisme causal.
Certaines de ces variations sont mieux adaptées au milieu naturel que
d'autres et favorisent la survie des individus, donc leur reproduction,
pendant que d'autres, moins adaptées au milieu, ne permettent pas une
survie suffisamment longue pour assurer la reproduction : ce mécanisme,
dit de sélection naturelle, est également causal. Les comportements les
mieux adaptés à l'environnement se trouvent donc être ceux qui résistent
au temps, non par l'effet d'une finalité mais par pur mécanisme. Il
n'est donc pas besoin de finalité pour expliquer ce qui, dans la nature,
semble bien fait. La nature\marginpar{Conclusion de s.-p.} n'est pas « bien »
faite : elle est simplement telle qu'elle est. C'est illusion que de
projeter sur elle des fins supposées.

Son fondement n'étant\marginpar{Thèse de s.-p.} pas épistémologique, l'idée
que la nature est bien faite repose en réalité sur un fondement
/métaphysique/​ : l'existence de Dieu. Dire que la nature est bien faite,
c'est en effet présupposer qu'elle a été faite par quelqu'un. Ce n'est
pas l'homme qui fait la nature puisque, par définition, la nature n'est
pas le résultat de l'activité humaine ; ce ne peut donc être qu'un
créateur supposé. Ainsi l'observation\marginpar{Référence} apparemment
innocente selon laquelle la nature est utile ou belle a-t-elle été
utilisée, par exemple par Bernardin de Saint-Pierre, pour démontrer
à partir de l'expérience commune l'existence de Dieu. L'argument repose
en réalité sur une pétition de principe : en supposant que la nature
contient des fins, on conclut que ces fins ont été fixées par un
créateur — mais c'est l'idée même de fin qui était d'emblée suspecte.
L'idée selon laquelle\marginpar{Conclusion de s.-p.} la nature serait bien
faite est donc non seulement dénuée de fondement épistémologique, ce qui
montre son arbitraire, mais contient en creux une thèse métaphysique.

Nous avions\marginpar{Conclusion de partie} vu que lorsque l'on dit que
la nature est bien faite, ce n'est pas de façon absolue mais en la
rapportant à des fins déterminées. Nous voyons maintenant que ces fins
ne sont pas elles-mêmes constatées dans la nature, mais que c'est nous
qui les projetons sur elle en nous appuyant non pas sur l'expérience que
nous invoquons, mais sur des principes métaphysiques. Les fins ne
peuvent être constatées ni dans la nature elle-même, ni hors d'elle dans
quelque intention divine. Faut-il donc\marginpar{Transition} renoncer à
donner un sens autre que métaphorique à l'idée que la nature est bien
faite, ou bien pouvons-nous lui donner un sens en la rapportant à des
fins avérées ?

#+BEGIN_CENTER
*

[À l'écrit : saut de lignes. À l'oral : silence de plusieurs secondes.]
#+END_CENTER

Puisque\marginpar{Thèse et plan} la nature ne peut être jugée bien faite
que relativement à certaines fins que l'homme projette librement sur
elle, nous verrons que certaines de ces fins permettent de juger si la
nature est bien faite : les fins de l'homme lui-même en tant que
responsable du devenir de la nature. Cela na nous conduire à préciser la
définition de la nature ainsi que le statut des fins que nous projetons
sur elle.

La nature\marginpar{Thèse de s.-p.} n'a certes pas initialement de fins,
conformément à sa définition comme ensemble des processus matériels ne
résultant pas d'une activité humaine. En soi, la nature n'est pas bien
ou mal faite car elle ne réalise aucun plan fixé d'avance : elle est
simplement telle qu'elle est. Mais cela ne l'empêche pas d'être, après
coup, investie de fins. Certains de ses habitants ayant acquis le
pouvoir d'influencer massivement son cours\marginpar{Argumentation},
c'est largement d'eux que dépend aujourd'hui le fait que la nature soit
bien faite ou non. Quelque arbitraires qu'elles soient, les fins
humaines n'en existent pas moins. Pour juger\marginpar{Conclusion de s.-p.}
si la nature est bien faite, on peut donc prendre pour critère
l'adéquation entre l'état de la nature et les intérêts de ses habitants,
à commencer par le plus puissant d'entre eux.

Cette perspective\marginpar{Thèse de s.-p.} nous conduit à préciser la
définition la nature en tenant compte de la responsabilité acquise par
l'homme dans l'histoire. La nature ne résulte\marginpar{Argumentation}
certes pas de l'activité humaine, dans la mesure où elle n'a pas été
créée par lui ; mais si son cours ne dérive pas de l'activité humaine,
aujourd'hui il en dépend largement. Les effets du changement climatique,
les disparitions d'espèces, la pollution sont si massifs que l'on
appelle désormais « anthropocène » l'époque de la planète Terre où
l'activité humaine affecte essentiellement son devenir. L'homme n'a pas
créé la nature mais la capacité qu'il a de la transformer l'en rend
responsable : l'état de la nature dépend de son action et il peut en
être blâmé. Impossible de dire sans lourde hypothèse métaphysique si la
nature était initialement bien faite ; mais ce qui est
certain\marginpar{Conclusion de s.-p.} est qu'il dépend désormais de
l'homme qu'elle le soit, et cette question est désormais d'ordre
politique.

Reste à fixer\marginpar{Thèse de s.-p.} le statut précis de la fin ainsi
projetée sur la nature, à savoir l'adéquation entre son état et les
intérêts de ses habitants. Pas plus que la nature, l'homme n'a reçu de
mission explicite. Il peut donc tout au plus « faire comme si » la
nature avait pour fin son adaptation à ses habitants. On fait alors, en
termes kantiens\marginpar{Référence}, un usage « régulateur » plutôt que
« constitutif » de la notion de finalité. Nous ne
pouvons\marginpar{Conclusion de s.-p.} affirmer que la nature soit bien
faite mais nous devons postuler, afin d'orienter notre action, qu'elle
doit le devenir.

#+BEGIN_CENTER
*

[À l'écrit : saut de lignes. À l'oral : silence de plusieurs secondes.]
#+END_CENTER


# * Conclusion 

# \section*{Conclusion}

Si l'on prend\marginpar{Analyse} en un sens théorique l'affirmation
selon laquelle la nature est bien faite, celle-ci est infondée : elle
consiste à examiner comme soumise à une finalité un objet qui par
définition en est dénué, ou à lui prêter des fins potentiellement
arbitraires.

L'histoire a pourtant transformé cette question théorique en question
politique : l'histoire ayant vu l'émergence d'une finalité humaine dotée
de moyens techniques susceptibles d'influer massivement le cours de la
nature, l'adéquation de celle-ci à des fins relève aujourd'hui non plus
seulement de la contemplation, mais avant tout de l'action et de la
responsabilité humaine.

L'homme ne\marginpar{Réponse claire} peut donc pas savoir si la nature
est bien faite, mais sait désormais qu'il doit agir pour qu'elle le
soit.

* Sujets de dissertation
<<sujets>>

Voici des sujets pour s'entraîner à la dissertation[fn:9]. Pour vous
entraîner, il suffit de rédiger :

1. une introduction : définitions, tension, problématique ;

2. un plan détaillé (aucun nom de philosophe ne doit apparaître dans les
   titres des parties et sous-parties) ;

3. une courte conclusion répondant clairement à la problématique.

On trouvera une liste plus complète dans le document du présent auteur,
« 11 000 sujets de dissertation de philosophie »
(http://baptiste.meles.free.fr/site/BMeles-9000_sujets_dissertation_philosophie.pdf).

\begin{multicols}{2}
\noindent Peut-on renoncer à comprendre ? \par
\noindent Y a-t-il une éducation du goût ? \par
\noindent L'extraordinaire \par
\noindent Qu'est-ce qu'un monstre ? \par
\noindent A qui devons-nous obéir ? \par
\noindent Peut-on échapper au temps ? \par
\noindent Pourquoi se divertir ? \par
\noindent Y a-t-il de l'impensable ? \par
\noindent Le possible \par
\noindent Qu'est-ce qu'une expérience? \par
\noindent Y a-t-il des limites à la conscience ? \par
\noindent La chance \par
\noindent L'incertitude \par
\noindent Qu'est-ce qu'être efficace en politique ? \par
\noindent Tout est-il politique ? \par
\noindent L'universel \par
\noindent Ai-je un corps ? \par
\noindent Ignorer \par
\noindent La métaphysique est-elle une science ? \par
\noindent Que nous apprennent les mythes ? \par
\noindent Qu'est-ce que traduire ? \par
\noindent Le désir de savoir est-il naturel ? \par
\noindent L'insurrection est-elle un droit ? \par
\noindent Y a-t-il des leçons de l'histoire ? \par
\noindent L'égalité est-elle une condition de la liberté ? \par
\noindent Le passé \par
\noindent La connaissance de soi \par
\noindent L'objet de l'amour \par
\noindent Pourquoi raconter des histoires ? \par
\noindent L'amour-propre \par
\noindent Qui suis-je ? \par
\noindent Existe-t-il un art de penser ? \par
\noindent La mort de Dieu \par
\noindent Connaître l'infini \par
\noindent L'homme est-il un loup pour l'homme ? \par
\noindent L'œuvre d'art doit-elle nous émouvoir ? \par
\noindent La vérité en art \par
\noindent Vérité et certitude \par
\noindent L'enfant et l'adulte \par
\noindent Les animaux pensent-ils ? \par
\noindent Le beau a-t-il une histoire ? \par
\noindent L'éternité \par
\noindent L'interprétation \par
\noindent Peut-on penser sans concept ? \par
\noindent Entendre raison \par
\noindent Qu'est-ce que faire preuve d'humanité ? \par
\noindent L'histoire a-t-elle un sens ? \par
\noindent L'aveu \par
\noindent Prévoir \par
\noindent Que recherche l'artiste ? \par
\noindent Peut-on rester sceptique ? \par
\noindent L'outil \par
\noindent Le vrai et le faux \par
\noindent Faut-il une théorie de la connaissance ? \par
\noindent L’acte et l’œuvre \par
\noindent Qu’est-ce qu'un réfutation ? \par
\noindent L’exception \par
\noindent Le bavardage \par
\noindent La philosophie est-elle abstraite ? \par
\noindent L’éternité \par
\noindent L’homme est-il raisonnable par nature ? \par
\noindent Peut-on tout dire ? \par
\noindent Y a-t-il des actes de pensée ? \par
\noindent Tuer le temps \par
\noindent L’imprévisible \par
\noindent Qu’y a-t-il ? \par
\noindent Qu’est-ce qu’un accident ? \par
\noindent L’opinion \par
\noindent La gauche et la droite \par
\noindent Le privé et le public \par
\noindent Peut-on tout démontrer ? \par
\noindent Quel est l’objet de l’histoire ? \par
\noindent La cohérence \par
\noindent Que nul n’entre ici s’il n’est géomètre. \par
\noindent Histoire et géographie \par
\noindent Voir \par
\noindent La conscience a-t-elle des moments ? \par
\noindent L’argument d’autorité. \par
\noindent La désobéissance \par
\noindent Rêvons-nous ? \par
\noindent L’inhumain \par
\noindent Qu’est-ce qu’un principe ? \par
\noindent Y a-t-il une langue de la philosophie ? \par
\noindent L’introspection est-elle une connaissance ? \par
\noindent L’homme est-il un animal comme les autres ? \par
\noindent La nature est-elle bien faite ? \par
\noindent L’ordre. \par
\noindent La démocratie \par
\noindent Peut-on penser sans ordre ? \par
\noindent Qu’est-ce qu’un monstre ? \par
\noindent Le temps existe-t-il ? \par
\noindent Qu’est-ce qu’un auteur ? \par
\noindent Qu’est-ce qu’être ? \par
\noindent Peut-on être sceptique ? \par
\noindent Qu’est-ce qu’interpréter ? \par
\noindent Qu’est-ce qu’un peuple ? \par
\noindent Peut-on séparer l’homme et l’œuvre ? \par
\noindent Peut-on ne pas être soi-même ? \par
\noindent À quoi reconnaît-on une œuvre d’art ? \par
\noindent La haine de la raison \par
\noindent Comment penser le mouvement ? \par
\noindent Y a-t-il des régressions historiques ? \par
\noindent Suis-je seul au monde ? \par
\noindent Qu’est-ce qu’un monde ? \par
\noindent La famille \par
\noindent Y a-t-il des guerres justes ? \par
\noindent Le mot juste. \par
\noindent L’identité collective \par
\noindent La loi \par
\noindent Qu’est-ce qu’une question ? \par
\noindent Qui fait l’histoire ? \par
\noindent Qu’est-ce qu’une maladie ? \par
\noindent L’irrationnel \par
\noindent Qu’est-ce qu’un auteur ? \par
\noindent Qu’est-ce qui fait la force de la loi ? \par
\noindent La superstition \par
\noindent Peut-on s’en tenir au présent ? \par
\noindent L’emploi du temps \par
\noindent Y a-t-il des expériences métaphysiques ? \par
\noindent Le spectacle de la nature \par
\noindent Habiter le monde \par
\noindent L’état de droit \par
\noindent La servitude \par
\noindent La perspective \par
\noindent Qu’est-ce qu’un monstre ? \par
\noindent La reconnaissance \par
\noindent Le beau a-t-il une histoire ? \par
\noindent L’événement \par
\noindent Plaisir et douleur \par
\noindent L’interprétation \par
\noindent La solitude \par
\noindent L’illusion \par
\noindent L’observation \par
\noindent La raison d’Etat \par
\noindent L’harmonie \par
\noindent Justice et force \par
\noindent Le paysage \par
\noindent Apprend-on à voir ? \par
\noindent L’habitude \par
\noindent La simplicité \par
\noindent Faut-il se délivrer de la peur ? \par
\noindent Faut-il vouloir la transparence ? \par
\noindent Le langage est-il un instrument ? \par
\noindent L’identité personnelle \par
\noindent L’avocat du diable \par
\noindent Peut-il y avoir un droit de la guerre ? \par
\noindent Qu’est-ce qu’une croyance rationnelle ? \par
\noindent La désobéissance civile \par
\noindent L’ennemi \par
\noindent Qu’est-ce qu’une décision politique ? \par
\noindent Penser par soi-même \par
\noindent Être hors de soi \par
\noindent Pourquoi punir ? \par
\noindent L’artiste est-il un créateur ? \par
\noindent Peut-on tout exprimer ? \par
\noindent Cause et loi \par
\noindent Qu’est-ce qu’un mythe ? \par
\noindent Pouvons-nous être objectifs ? \par
\noindent L’étranger \par
\noindent L’imaginaire \par
\noindent Quel usage peut-on faire des fictions ? \par
\noindent Faire la paix \par
\noindent Le mouvement \par
\noindent La loi et la coutume \par
\noindent Quel est l’objet de l’amour ? \par
\noindent Qu’est-ce qu’une crise ? \par
\noindent Apprend-on à être artiste ? \par
\noindent L’oubli \par
\noindent L’amour de la vérité \par
\noindent Les œuvres d’art sont-elles éternelles ? \par
\noindent Le hasard \par
\noindent Peut-on être citoyen du monde ? \par
\noindent Y a-t-il des limites à la connaissance ? \par
\noindent L’apparence \par
\noindent La critique \par
\noindent La souveraineté peut-elle se partager ? \par
\noindent Qu’est-ce qui est réel ? \par
\noindent La justice sociale \par
\noindent L’immortalité \par
\end{multicols}

# ** L'art

# Pourquoi conserver les œuvres d'art ?

# L'art imite-t-il la nature ?

# L'éducation esthétique

# L'inspiration

# L'artiste sait-il ce qu'il fait ?

# L'art et la morale

# Le plaisir esthétique suppose-t-il une culture ?

# La virtuosité

# Qu'est-ce qu'une œuvre ratée ?

# Y a-t-il un progrès en art ?

# Le génie

# Le mauvais goût

# Arts de l'espace et arts du temps

# L'art engagé

# La pluralité des arts

# La vérité de l'œuvre d'art

# ** Logique et épistémologie

# Mécanisme et finalité

# Le symbolisme mathématique

# Le hasard n'est-il que la mesure de notre ignorance ?

# Comment choisir entre plusieurs hypothèses ?

# La logique nous apprend-elle quelque chose sur le langage ordinaire ?

# La causalité

# Sauver les phénomènes

# Les genres naturels

# Qu'est-ce qu'un nombre ?

# La cohérence est-elle un critère de vérité ?

# Des événements aléatoires peuvent-ils obéir à des lois ?

# L'intuition en mathématiques

# La contradiction

# La logique a-t-elle une histoire ?

# Y a-t-il plusieurs logiques ?

# La méthode

# Savoir et pouvoir

# ** La métaphysique

# L'impossible

# L'être et le temps

# Y a-t-il une connaissance métaphysique ?

# Seul le présent existe-t-il ?

# N'y a-t-il qu'un seul monde ?

# L'existence se démontre-t-elle ?

# Avons-nous une âme ?

# L'infinité du monde

# Que prouvent les preuves de l'existence de Dieu ?

# Le virtuel et le réel

# Le réel est-il rationnel ?

# Être et être pensé

# Penser sans corps

# Le miracle

# Logique et métaphysique

# Dieu a-t-il pu vouloir le mal ?

# ** La morale

# Sommes-nous responsables de notre passé ?

# Le repentir

# Peut-on conclure de l'être au devoir-être ?

# L'intolérable

# Le péché

# La beauté morale

# Peut-on vouloir le mal ?

# La morale peut-elle être fondée sur la science ?

# Y a-t-il un devoir d'être heureux ?

# La morale peut-elle se passer d'un fondement religieux ?

# La moralité n'est-elle que dressage ?

# La morale peut-elle être un calcul ?

# Le moi est-il haïssable ?

# ** La politique

# Guerre et politique

# La rationalité politique

# Qu'est-ce qu'un contre-pouvoir ?

# Le totalitarisme

# Que faut-il savoir pour gouverner ?

# Le législateur

# Le respect des institutions

# Les droits de l'homme sont-ils une abstraction ?

# La meilleure constitution

# A-t-on des droits contre l'État ?

# Qu'est-ce qu'un programme politique ?

# Y a-t-il des erreurs en politique ?

# ** Les sciences humaines

# Histoire et ethnologie

# Les sciences humaines permettent-elles de comprendre la vie d'un homme ?

# Les sciences humaines sont-elles dangereuses ?

# Expliquer et comprendre

# Qu'est-ce qui rend l'objectivité difficile dans les sciences humaines ?

# Sciences humaines et philosophie

# L'efficacité thérapeutique de la psychanalyse

# La psychanalyse est-elle une science ?

# Sciences humaines et liberté sont-elles compatibles ?

# Y a-t-il une causalité historique ?

# L'objectivité de l'historien

# L'arbitraire du signe

# Machines et mémoire

# Les sciences humaines permettent-elles d'affiner la notion de
# responsabilité ?

# L'économie a-t-elle des lois ?

# L'argent

# Y a-t-il un inconscient collectif ?


* Enseigner la méthode de la dissertation
Cette section, à vocation didactique, n'est pas destinée aux élèves et
étudiants mais à leurs enseignants. On y trouvera le témoignage,
nécessairement partiel, d'une expérience particulière de l'enseignement
de la méthode de la dissertation exposée dans les pages
précédentes[fn:10].

Les principes de cette méthode d'enseignement sont les suivants : 
1. construire la dissertation dans l'ordre des moments qui la
   composent : d'abord l'introduction, ensuite le plan, enfin la
   conclusion ;
2. segmenter la construction de chacun de ces grands moments en petites
   étapes ;
3. travailler collectivement en effectuant parallèlement chacune de ces
   petites étapes puis en synchronisant le travail à l'échelle de la
   classe, ce qui permet d'éviter le blocage, la stigmatisation
   personnelle, ou l'effet dissuasif du « corrigé inaccessible » ;
4. l'enseignant, qui idéalement n'a pas préparé de corrigé à l'avance,
   réfléchit en même temps que les étudiants et insère ses propositions
   dans la liste, sur le même plan que celles des étudiants.

Nous décrirons ici les séances-types de travail sur l'introduction, sur
le plan et sur la conclusion. 

** Enseignement de l'introduction

L'enseignant arrive avec un sujet ou une liste de sujets qu'il n'a pas
travaillés à l'avance. Une fois le sujet choisi, il l'écrit au tableau.

La première étape est celle de la construction de l'introduction. Elle
se compose de deux sous-étapes : les définitions et la problématisation. 

Pour les définitions, chacun doit identifier les termes à définir[fn:11],
puis écrire une définition sur son brouillon. Une fois la définition
écrite, chacun vérifie pour lui-même si elle consensuelle, nécessaire,
suffisante et non-circulaire[fn:12]. Lorsque tout le monde est parvenu à
une définition, même insatisfaisante (ce qui prend environ 5 minutes par
terme), on effectue un tour de table en écrivant au tableau les
différentes définitions (prévoir 20 à 30 minutes). On vérifie en même
temps si elles satisfont les quatre critères d'une bonne définition ;
on peut souligner par des vaguelettes les éventuels points de fragilité
tels qu'un risque de circularité et proposer de les corriger en
modifiant le plus légèrement possible la définition. À la suite des
propositions des étudiants, l'enseignant écrit la sienne — parfois moins
bonne que celles d'étudiants[fn:13]. On répète l'opération pour chaque
terme-clef du sujet.

(Au terme de cette étape, les étudiants voient qu'il existe plusieurs
manières de définir un même terme, ce qui montre qu'il n'y a pas une
unique formule qui était attendue d'eux comme un corrigé. Ils voient
également les formes variées que peuvent prendre la circularité et
autres défauts, ce qui les aide à être plus vigilants à l'avenir sur
leur propre production.)

Ensuite vient la seconde sous-étape de l'introduction :
la problématisation. L'exercice suivant est de construire la
problématisation en s'appuyant uniquement sur deux ressources : les
définitions que l'on a choisies (les siennes, celles de l'enseignant ou
celles de camarades) et les thèses du sens commun. Chacun des
participants doit construire l'ébauche des deux paragraphes de
problématisation, en montrant comment les définitions et le sens commun
nous conduisent à une contradiction apparente :
#+BEGIN_QUOTE
Il semble, au premier abord, que $p$. En effet, ...

Cependant, on ne peut pas affirmer que $p$, puisque...
#+END_QUOTE
Cette tâche prend environ 10 minutes. On écoute ensuite les différentes
propositions, y compris celle de l'enseignant. On pointe les éventuelles
améliorations possibles dans les différentes propositions.

L'enseignant peut enfin rédiger au tableau une introduction en prenant
les définitions et la problématisation de son choix — y compris parmi
celles proposées par les étudiants.

(Ce travail par petites étapes permet, individuellement, d'effectuer un
travail ciblé sur chaque moment de l'introduction pris isolément.
Collectivement, Il favorise la discussion, l'argumentation, le travail
en commun, l'écoute.)


** Enseignement du plan

Pour enseigner la construction du plan, l'idée principale est de montrer
aux étudiants que le plan se conçoit en allant du général (les thèses de
parties) au particulier (les arguments, références et exemples), et non
l'inverse comme on le fait souvent.

Le professeur commence par soumettre aux étudiants une introduction avec
annonce du plan[fn:14]. 

La première étape est l'invention des sous-parties. On commence par la
première partie : grâce à l'annonce du plan, les étudiants savent quelle
thèse ils doivent y soutenir. Le premier exercice (en 5 à 10 minutes)
est de trouver sur leur brouillon les titres des sous-parties. Ces
titres doivent être des thèses dont la succession permette de démontrer
la thèse de la partie ; ils ne doivent pas contenir de nom d'auteur. On
met ensuite en commun les différentes propositions de sous-parties de la
première partie. On répète l'opération pour chaque partie.

La seconde étape est le recueil des arguments. On choisit une des
sous-parties. Tout le monde doit réunir sur son brouillon des arguments,
références ou exemples à l'appui de cette thèse. 

Une fois le travail terminé sur tout ou partie du plan, on peut proposer
un corrigé en choisissant parmi les produits du travail collectif.


** Enseignement de la conclusion 

Pour travailler la conclusion, l'enseignant soumet aux étudiants une
introduction avec annonce de plan[fn:15]. Ils doivent ensuite
(en 10 minutes environ) rédiger une courte conclusion résumant la copie,
sous les deux contraintes suivantes : 

1. une phrase doit répondre clairement à la problématique ;
2. la conclusion ne doit contenir aucun connecteur temporel (d'abord,
   ensuite, enfin...), mais uniquement des connecteurs logiques (si...
   alors, même si..., il pourrait sembler que... mais en réalité...).


** Points d'amélioration de cette méthode d'enseignement 

Deux aspects de la construction d'une dissertation ne sont pas
travaillés dans l'exercice ci-dessus : 
1. l'invention des titres de grandes parties (par opposition aux
   sous-parties) ;
2. la rédaction des transitions.

* Footnotes

[fn:1] Certains correcteurs sanctionnent explicitement d'un ou deux points
    une orthographe défaillante. Ceux qui ne le font pas sont souvent
    plus sévères : l'impression générale de négligence que délivre la
    copie les incite à en retirer implicitement bien plus.

# [fn:23] Kant, /Logique/, §107.

[fn:2] Aristote, /Topiques/, IV, 101b20 ; V, 101b35--102a20.

[fn:3] Kant, /Logique/, §109.

[fn:4] On trouvera un exemple de cette méthode dans l'exposition par
Épictète de l'argument Dominateur (Épictète, /Entretiens/, II, 19). Voir
l'analyse de Jules Vuillemin, /Nécessité ou contingence/, Paris,
Minuit, 1984.

[fn:5] En logique classique, on peut montrer que la négation de « A et B
et C » implique « non A ou non B ou non C ».

[fn:6] Ce qui, au passage, montre l'utilité directe, pour la dissertation,
    de la logique : celle-ci n'est pas une discipline isolée du cursus,
    elle est proprement philosophique.

[fn:7] Gilles-Gaston Granger, /Essai d'une philosophie du style/, Paris,
    Armand-Colin, Philosophies pour l'âge de la science, 1968, p. 7.

[fn:8] Ainsi, dans l'/Anthropologie/ (II, B), Kant définit la féminité par
    deux critères : la conservation de l'espèce (qui implique la crainte
    et la faiblesse), et l'affinement de la culture (qui implique la
    politesse et la tendance au bavardage).

[fn:9] Ces sujets sont tirés du rapport du jury du concours oral pour
l'année 2018 de l'École normale supérieure de Paris
(http://www.ens.fr/sites/default/files/2018_al_philo_oral_epreuve_commune.pdf).
Les sujets ont été proposés par Fabienne Baghdassarian, François Calori,
Pascale Gillot, Laurent Lavaud, Baptiste Mélès et Pauline Nadrigny.

[fn:10] Cette méthode a été appliquée principalement dans le cadre de
cours de Méthodologie du travail universitaire en Licence 1 et 2
de philosophie à l'Université de Lorraine ainsi qu'à l'université
Toulouse-3, devant 10 à 50 étudiants en présentiel ou en
vidéoconférence. Ce contexte est assez privilégié car le public est
motivé et respectueux. Nous laisserons chaque professeur juger si ces
méthodes d'enseignement sont ou non applicables à sa situation
particulière, et dans quelle mesure elles doivent y être adaptées.

[fn:11] Ceci ne pose généralement aucun problème : tous les étudiants
repèrent facilement quels sont les termes-clefs d'un sujet.

[fn:12] Les définitions sont souvent assez consensuelles et nécessaires,
mais plus rarement suffisantes et non-circulaires. Il faut donc, comme
indiqué plus haut, dans le premier cas ajouter des critères, et dans le
second remplacer le terme circulaire par sa définition.

[fn:13] L'enseignant ne perd pas de crédibilité en avouant qu'une autre
proposition est meilleure que la sienne — bien au contraire.

[fn:14] Cette introduction peut être celle qui a été produite dans
l'exercice précédent, mais ce n'est pas nécessaire.

[fn:15] Ce peut être, mais pas nécessairement, l'introduction construite
puis utilisée dans les exercices précédents.

[fn:16] Nietzsche, /Par-delà bien et mal/, §36.

