#+TITLE:     Méthode de la dissertation philosophique
#+AUTHOR:    Baptiste Mélès
#+EMAIL:     baptiste.meles@gmail.com
#+DATE:      4 octobre 2019
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  fr
#+OPTIONS:   H:4 num:t toc:3 \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+LATEX_HEADER: \usepackage[frenchb]{babel}
#+LATEX_HEADER: \usepackage{lmodern}
#+LATEX_HEADER: \usepackage{multicol}
#+LATEX_HEADER: \DeclareUnicodeCharacter{00A0}{~}
#+LATEX_HEADER: \DeclareUnicodeCharacter{200B}{}

L'objectif de la dissertation de philosophie est de soulever un problème
sur un sujet donné, et d'y proposer une réponse éclairée.


* Le brouillon

La composition d'une dissertation a lieu en trois moments : le
brouillon, la rédation, la relecture. Cette dernière, souvent négligée,
est pourtant cruciale, notamment pour corriger l'orthographe [1].

** Gestion du temps

Le brouillon est un moment essentiel de la dissertation. Il faut donc
lui consacrer suffisamment de temps, sans pour autant menacer la qualité
de la rédaction.

On dispose généralement de quatre heures en licence pour composer une
dissertation, et de sept heures pour l'agrégation. On doit ménager un
temps important pour la rédaction, car dans la précipitation, il est
presque impossible de réfléchir efficacement. On peut donc consacrer 1h
ou 1h30 au brouillon en licence (donc 2h30 ou 3h pour la rédaction), 3h
pour l'agrégation (donc 4h pour la rédaction).

L'idéal est d'avoir terminé la rédaction avec au moins 15 minutes
d'avance en licence, 30 minutes pour l'agrégation ; on se réserve ainsi
un temps suffisant pour la relecture.

** Problématisation puis accumulation des idées

La première chose à faire est de noter sur le brouillon une ou plusieurs
/définitions/ pour chacun des termes importants du point de vue du sens
commun.

Ensuite, on cherche dans les définitions quelle est la tension qui
donnera naissance à la /problématique/.

Enfin, il faut noter sur le brouillon toutes les /idées/ --- les thèses,
les auteurs, les références --- à mesure qu'elles nous viennent à
l'esprit, sans les sélectionner. Le tri s'effectuera spontanément plus
tard.

Évitez de commencer l'accumulation des idées avant d'avoir clairement
cerné les définitions et la problématique. Sinon, vous risquez perdre
beaucoup de temps pour noter des idées qui seront finalement hors sujet
et que vous essaierez de caser à toute force dans la dissertation pour
rentabiliser l'effort et le temps perdus.

** Composition du plan

Une fois que l'on a suffisamment d'idées et que leur organisation
commence à se préciser dans notre esprit, on peut passer à la
constitution du plan.

Chaque partie du plan doit pouvoir être formulée par une thèse
explicite, et, si possible, par des « formules » facilement
reconnaissables (on en trouvera quelques exemples ci-dessous : la
substance comme substrat, comme fiction, ou comme fonction ; la guerre
comme déchaînement de violence, comme violence rationnelle, ou comme
violence raisonnable ; etc.).

Le plan doit contenir toutes les parties et les sous-parties ; il n'est
pas nécessaire de pousser la subdivision trop loin. Chaque partie ou
sous-partie doit comporter un titre exprimant la thèse locale en cinq à
dix mots (par exemple « I - La substance comme substrat », « A) le primat
ontologique de la substance », « B) le primat chronologique de la
substance », « C) le primat chronologique de la substance », « II - La
substance comme illusion »).

Enfin, dans le plan, on doit noter avec soin la structure de chacune des
transitions. Cette précaution garantit que le passage d'une partie à une
autre ne sera pas artificiel ou simplement rhétorique.

** Introduction et conclusion

Une fois le plan terminé, il est recommandé de rédiger intégralement au
brouillon l'introduction et la conclusion. Ainsi, si l'on est pris par
le temps en fin de rédaction, on n'aura plus qu'à recopier la
conclusion, et la dissertation se terminera proprement, même si dans le
développement l'on n'a pas eu le temps d'écrire en détail tout ce que
l'on espérait.

* Introduction

L'introduction doit être la présentation, progressive et détaillée, de
la problématique.

Il vaut mieux éviter d'y citer des noms de philosophes : ceux-ci sont
rigoureusement étrangers à la problématisation de la question, même si
plus tard ils vous seront évidemment très utiles pour proposer des
réponses. Partir de l'état de la littérature philosophique serait
inverser le juste ordre des choses : il faut aller des problèmes à la
philosophie, non de la philosophie aux problèmes. Dans l'introduction
--- comme plus tard dans la conclusion --- l'étudiant doit assumer ses
responsabilités, n'engager que soi, mais s'engager totalement. Une bonne
introduction ne contient aucun nom de philosophe.

Une introduction est généralement composée des parties suivantes,
chacune pouvant être présentée en un alinéa :

1. l'/amorce/ (très facultative) ;

2. l'/analyse/ des termes du sujet (en un petit nombre de phrases) ;

3. la mise au jour d'une /tension/ entre les termes du sujet (plusieurs
   phrases bien développées) ;

4. la /problématique/ (une question unique) ;

5. l'/annonce du plan/ (une phrase par partie) ;

6. la présentation des /enjeux/ de cette problématique (très
   facultative).

Il faut apporter un soin particulier à l'introduction, et plus tard à la
conclusion, car ce sont les deux parties qui marquent le plus les
correcteurs. Une introduction bancale ou expéditive laissera une
impression négative que le meilleur développement du monde ne saura
dissiper.

Une bonne introduction occupe généralement entre une demi-page (surtout
en licence) et une page entière (principalement pour l'agrégation).
À plus d'une page et demie, elle commence à trop s'étirer : les
questions partent dans tous les sens, parce que le candidat n'arrive pas
à resserrer son étude sur une problématique unique.

** L'amorce

On préconise parfois de recourir à une amorce avant de définir les
termes du sujet, sous prétexte que l'entrée dans la dissertation est
moins abrupte. On peut ainsi partir d'une anecdote, d'un exemple tiré du
quotidien, d'un exemple historique, etc. Par exemple, pour le sujet « La
guerre », on peut partir d'une comparaison entre deux figures
historiques :

#+BEGIN_QUOTE
  Jean Jaurès est mort pour avoir refusé la guerre quand son pays la
  désirait, Jean Cavaillès pour l'avoir acceptée quand son pays y avait
  renoncé : aujourd'hui ils sont tous deux reconnus comme des « justes ».
  De ce constat paradoxal on peut tirer deux interrogations : la
  première porte sur la nature de la guerre, la seconde sur les moyens
  de son évaluation morale et politique.
#+END_QUOTE

L'ensemble de la dissertation pourra donc être vu comme la tentative
d'explication de ce simple constat : que Jaurès et Cavaillès, avec des
comportements apparemment opposés, puissent être l'objet des mêmes
éloges.

Il vaut mieux éviter de partir directement de l'histoire de la
philosophie, en disant par exemple que Hobbes justifie la guerre par
l'état de nature, etc. La dissertation, dans l'introduction, doit pour
ainsi dire s'appuyer sur la fiction que la philosophie n'ait pas
préexisté à notre réflexion. La diversité des opinions philosophiques
n'est jamais un bon point de départ de dissertation : l'interrogation
sur le sexe des anges a beau avoir suscité bien des opinions contraires,
elle n'en a pas le moindre intérêt pour autant.

Mais l'amorce est hautement facultative. En cas de manque d'inspiration,
il vaut mieux en faire totalement l'économie que de la rédiger
maladroitement.

** L'analyse des termes du sujet

*** Définition

Quand on n'utilise pas d'amorce spécifique, l'analyse des termes du
sujet est le début de la dissertation ; dans ce cas, il ne faut pas
hésiter à commencer /ex abrupto/ par la définition des concepts.
L'introduction est alors sobre mais efficace.

L'analyse des termes du sujet consiste à prendre chaque terme important
de l'énoncé et à le définir, fût-ce simplement de manière préalable.
Dans le sujet « La guerre », on peut définir en première approche la
guerre comme « le conflit armé entre deux groupes humains ».

**** Réversibilité des définitions

Même en première approche, une définition n'en est pas une si l'on ne
peut aller du concept à la définition, /et surtout/ de la définition au
concept [2]. Supposons que l'on dise par exemple « la guerre, c'est le
conflit ». Certes, la guerre est un conflit (on peut donc aller du
concept à la définition), mais tout conflit n'est pas une guerre : il
existe également des conflits entre collègues de travail, entre membres
d'une famille, entre mâles dominants dans un troupeau, et ces conflits
ne sont pas des guerres (on ne peut donc pas aller de la définition au
concept). Il faut donc trouver, parmi l'ensemble des conflits, ce qui
distingue la guerre en particulier. Nous avons retenu deux critères : le
fait que le conflit oppose des hommes, et qu'il soit armé ; mais
d'autres définitions sont certainement possibles.

**** Ne pas thématiser le sujet

Évitez de mentionner explicitement « le sujet » ou « l'intitulé », par
exemple en disant « Ce sujet nous propose de réfléchir sur... » ou « Le
présupposé de ce sujet est... ». Commencez directement par l'analyse des
termes.

**** Donner les définitions du sens commun

Les définitions que vous donnez en introduction doivent être celles du
sens commun. Elles ne doivent surtout pas être celles d'un philosophe et
encore moins présupposer une thèse philosophique particulière. Par
exemple, ne définissez pas « Dieu » comme une entité immanente à la nature
(que vous pensiez ou non à Spinoza) car ce n'est généralement pas en ce
sens que l'on utilise ce terme. Vos définitions en introduction doivent
être œcuméniques et être acceptées comme des évidences par la première
personne rencontrée dans la rue.

**** Comment définir les termes polysémiques

Souvent, un terme à définir possède plusieurs significations. Deux cas
de figure se présentent alors. 

1. Si toutes les significations sont liées les unes aux autres, allez du
   multiple à l'un, c'est-à-dire commencez par donner les différentes
   définitions, puis montrez quelle essence elles ont en commun (par
   exemple, pour le sujet « La corruption », vous pouvez chercher une
   essence commune aux emplois métaphysique, botanique et politique du
   mot).
2. Si, à l'inverse, les différentes significations sont relativement
   indépendantes les unes aux autres, distinguez clairement les
   différents emplois et éliminez ceux qui ne sont pas pertinents (par
   exemple, pour le sujet « Le corps peut-il être objet d'art ? », vous
   pouvez stipuler dès l'introduction que vous entendrez le corps
   exclusivement dans le sens de « corps humain » et non dans le sens
   métaphysique d'un individu matériel).

**** Sujets définitionnels

Il arrive que tout l'enjeu d'un sujet de dissertation soit précisément
de définir un concept, notamment quand il commence par « qu'est-ce que » :
« Qu'est-ce que le bonheur ? », « Qu'est-ce qu'agir ? », « Qu'est-ce qu'une
chose ? », etc. Dans ce cas, le concept doit recevoir /deux/
définitions : une première approximation en introduction, qui représente
ce que l'on entend généralement par ce concept, et une définition
approfondie qui sera donnée en conclusion du devoir. Ainsi, même quand
la définition est l'enjeu même de la dissertation, il faut
impérativement définir le concept dès l'introduction.

**** Sujets à plusieurs concepts

Lorsque le sujet comporte plusieurs concepts (« Bonheur et vertu », « Toute
pensée est-elle un calcul ? », « L'histoire est-elle une science ? »,
« Qu'est-ce qu'une action réfléchie ? »), on peut les définir l'un à la
suite de l'autre :

#+BEGIN_QUOTE
  Par pensée, on entend généralement l'ensemble de l'activité théorique
  de l'homme. Le calcul, quant à lui, est une démarche déductive
  reposant sur la manipulation de signes.
#+END_QUOTE

**** Éviter la circularité

Il faut prendre garde à éviter toute circularité dans la définition. Par
exemple, définir la pensée comme « activité /mentale/ du sujet » serait
s'exposer à la question de savoir ce qu'est à son tour l'« activité
mentale »... et à la réponse spontanée : « l'activité mentale est
l'activité de la /pensée/ ». La définition est circulaire ! Elle
transformait simplement un substantif (« pensée ») en adjectif
(« mental »). De même, définir l'animal en commençant par dire qu'il est
un être « biologique » ou « doué de vie », « animé » ou « possédant une
âme » (/anima/), ce n'est que déplacer toute la difficulté dans l'un de
ces mots. Cas extrême de circularité, le Père Étienne Noël définissait
en 1647 la lumière comme « un mouvement luminaire de rayons composés de
corps lucides, c'est à dire lumineux ».

La définition doit partir du sens commun et être éclairante ; par
exemple, on peut proposer de définir l'animal comme « un être capable de
se déplacer et de viser ses propres fins » : on a ainsi défini le
concept par des mots strictement plus simples.

Pour résumer, voici les conditions d'une bonne définition telles que les
a énumérées Kant :

#+BEGIN_QUOTE
  Ces mêmes opérations auxquelles il faut se livrer pour mettre à
  l'épreuve les définitions, il faut également les pratiquer pour
  élaborer celles-ci. --- À cette fin, on cherche donc 1) des
  propositions vraies 2) telles que le prédicat ne présuppose pas le
  concept de la chose 3) on en rassemblera plusieurs et on les comparera
  au concept de la chose même pour voir celle qui est adéquate 4) enfin
  on veillera à ce qu'un caractère ne se trouve pas compris dans l'autre
  ou ne lui soit pas subordonné [4].
#+END_QUOTE

*** Tension et problématique

**** Des définitions à la tension

L'analyse des termes du sujet n'est pas un procédé artificiel : il
possède une réelle utilité dans la construction de la dissertation ---
et en premier lieu, il empêche bien des hors-sujet. C'est en effet de
ces définitions que l'on doit extraire une /tension/, c'est-à-dire un
conflit. Quand le sujet comporte plusieurs concepts, le conflit apparaît
généralement entre eux quand on essaye de les associer ; quand le sujet
comporte un seul concept, le conflit apparaît souvent entre les termes
mêmes de la définition. C'est ce conflit qui engendre la
/problématique/. Sans tension, il n'est pas de problématique efficace :
sans tension, on voit difficilement l'intérêt de se poser telle ou telle
question --- et /a fortiori/ d'y répondre.

Voici un exemple pour le sujet « Toute pensée est-elle un calcul ? » :

#+BEGIN_QUOTE
  Par pensée, on entend généralement l'ensemble de l'activité théorique
  de l'homme. Le calcul, quant à lui, est une démarche déductive
  reposant sur la manipulation de signes. Or, l'histoire récente montre
  qu'un nombre croissant d'activités autrefois réservées à
  l'intelligence humaine --- opérations mathématiques, inférences
  logiques, prises de décisions économiques --- se voient déléguées à
  des machines, dont le fonctionnement repose pourtant sur le seul
  calcul. On peut donc s'interroger sur l'existence de limites à cette
  tendance historique. L'activité théorique de l'homme peut-elle être
  simulée tout entière par la simple manipulation de signes qui
  caractérise le calcul ?
#+END_QUOTE

La problématique ne doit surtout pas être conçue comme elle l'est
généralement, à savoir comme une question qui ressemble vaguement au
sujet que l'on nous a imposé sans toutefois lui être rigoureusement
identique. /La problématique n'est rien d'autre que l'explicitation de
ce qui, dans le sujet tel qu'il est posé, pose un problème./ 

Pour trouver la problématique, voici la méthode que nous vous
recommandons de suivre sur le brouillon :

1. /définition/ : je définis les principaux termes du sujet au moyen de
   concepts strictement plus simples ;

2. /substitution/ : je réécris le sujet en remplaçant chaque terme
   défini par sa définition ;

3. /tension/ : je trouve où réside la tension dans le sujet ainsi
   reformulé et j'en tire la problématique.

Voici un exemple pour le sujet « Dieu a-t-il pu vouloir le mal ? » :

1. /définitions/ des principaux termes :

   -  Dieu : créateur du monde possédant toutes les perfections ;

   -  le mal : ce qui ne doit pas être réalisé pour des raisons
      morales ;

2. /substitution/ des définitions aux termes définis dans le sujet : un
   /créateur du monde possédant toutes les perfections/ a-t-il pu
   vouloir /ce qui ne doit pas être réalisé pour des raisons morales/ ?

3. maintenant la /tension/ apparaît sans doute plus clairement : comment
   un être possédant toutes les perfections a-t-il pu vouloir un monde
   apparemment imparfait ?

On peut alors rédiger l'introduction :

#+BEGIN_QUOTE
  Par Dieu, on entend généralement un être qui d'une part est créateur
  du monde et de l'autre possède toutes les perfections, c'est-à-dire
  toutes les qualités positives à leur degré ultime. Le mal est ce qui
  ne doit pas être réalisé pour des raisons morales. Dieu possédant
  toutes les perfections, il est supposé infiniment bon, et par
  définition ne devrait pas pouvoir accomplir le mal. Un rapide coup
  d'œil autour de nous semble pourtant nous présenter le mal comme l'un
  des principaux ingrédients du monde dont Dieu serait le créateur :
  partout la guerre, l'injustice, la mort. L'hypothèse de l'existence
  d'un dieu bon est-elle donc compatible avec celle d'un monde
  apparemment mauvais ?
#+END_QUOTE

L'enjeu du devoir sera, dans chacune des parties, de proposer une
réponse à cette question et à elle seule. On peut ainsi proposer dans
une partie l'hypothèse selon laquelle un monde absolument parfait était
irréalisable, dans une autre l'hypothèse selon laquelle notre monde
n'est en réalité pas imparfait comme il semble l'être, etc.

**** Exemples

Voici trois exemples de définitions et de problématiques différentes
pour le sujet « La science » :

#+BEGIN_QUOTE
  1. (Définition externe, plutôt sociologique)

  Une science se présente généralement à nous comme un ensemble
  d'assertions qui devrait unanimement être reconnu comme vrai, et que
  l'on suppose avoir déjà fait consensus dans une communauté de
  spécialistes tels que les mathématiciens, les physiciens ou les
  sociologues. Mais le simple consensus ne fait pas la vérité.
  Existe-t-il donc à ce présumé consensus (c'est-à-dire de fait) un
  fondement nécessaire (c'est-à-dire de droit), qui soit commun à tout
  ce que nous appelons couramment des sciences ?

  2. (Définition interne, plutôt épistémologique)

  Une science est un ensemble de savoirs que l'on peut obtenir, puis
  vérifier, selon des principes méthodologiques déterminés à l'avance.
  Ces principes sont par exemple les axiomes et les règles de
  démonstration du mathématicien ; ou les théories, les concepts et les
  formules du physicien ; ou les concepts, les observations et les
  statistiques du sociologue. La science n'est donc pas une simple
  connaissance, c'est une connaissance par méthode. Ces principes de
  méthode semblent pourtant eux-mêmes échapper à tout contrôle, n'étant
  généralement pas remis en cause dans le cours normal de la science. À
  quelles conditions l'obéissance à des principes de méthode peut-elle
  donc valoir comme un garant de vérité ?

  3. (Définition naïve et empirique --- parfois très efficace)

  Nous appelons sciences un ensemble de discours tous tenus pour « vrais »
  et pourtant de natures très variées, qui comprend notamment des
  sciences pures comme les mathématiques et la logique, des sciences de
  la nature comme la physique et la biologie, des sciences humaines
  comme la psychologie et la sociologie. Certaines de ces « sciences »
  semblent unanimement reconnues comme telles et font autorité, d'autres
  font l'objet de débats passionnés --- la psychanalyse, l'histoire, le
  marxisme ---, tandis que d'autres prétendus savoirs sont presque
  unanimement classés parmi les « pseudo-sciences » --- l'astrologie,
  l'alchimie, la physiognomonie. Existe-t-il donc des critères
  universellement valides qui nous permettraient de déterminer avec
  certitude si un domaine de savoir relève ou non de la science ?
#+END_QUOTE

**** La problématique : une question unique

La problématique doit être présentée sous la forme d'une question
terminée par un point d'interrogation. Cette question ne doit pas être
la répétition pure et simple du sujet, si celui-ci était déjà sous forme
interrogative. Par exemple, pour le sujet « Toute pensée est-elle un
calcul ? », la problématique ne doit surtout pas être « Toute pensée
est-elle un calcul ? », mais être reformulée d'une manière éclairée par
les définitions préalables, comme dans l'exemple précédent : « L'activité
théorique de l'homme peut-elle être simulée tout entière par la simple
manipulation de signes qui caractérise le calcul ? ». Entre le sujet et
la problématique, on a progressé ; et ce, grâce aux définitions, qui
permettent de mieux comprendre où se loge véritablement le problème.

Enfin, la problématique doit consister en /une seule/ question. On a
parfois la tentation d'en formuler plusieurs : « L'activité théorique de
l'homme peut-elle être simulée tout entière par la simple manipulation
de signes qui caractérise le calcul ? Les machines peuvent-elles tout
faire ? L'homme sera-t-il remplacé à terme par des ordinateurs ? ». Mais
cette succession de questions angoissées témoigne parfois d'une absence
de choix, d'une hésitation entre plusieurs problématiques, et de leur
simple juxtaposition. Le correcteur ne sait pas si elles sont toutes
subordonnées à la première, si elles en précisent progressivement le
sens (et dans ce cas c'est la dernière qui doit être retenue comme
problématique définitive), ou encore si elles étudient trois aspects
d'une seule et même problématique, qui quant à elle ne serait pas
mentionnée. Il faut donc en choisir une seule ; c'est ce qui garantit
l'unité de la dissertation.

** Types de sujet

Il existe principalement quatre types de sujet :

1. /un seul concept/ (ou une expression) : « La substance », « L'égalité »,
   « Le génie », « Être impossible », « Voir », « Faire de nécessité vertu »,
   etc.

2. /deux concepts/ (ou, plus rarement, trois) : « Substance et
   accident », « Genèse et structure », « Corps et esprit »,
   « Convaincre et persuader », « Foi et raison », « Langue et parole »,
   « Conscience et inconscient », « Pensée et calcul », « Mathématiques
   et philosophie », « Ordre, nombre, mesure », etc.

3. /une question/ : « Toute philosophie est-elle systématique ? »,
   « Peut-on prouver l'existence de Dieu ? », « Peut-on penser l'histoire
   de l'humanité comme l'histoire d'un homme ? », etc.

4. /une citation/ : « « Si Dieu existe, alors tout est permis » »,
   « « La science ne pense pas » », « ``Pourquoi y a-t-il quelque chose
   plutôt que rien ?'' », etc.

Naturellement, différentes formulations peuvent être à peu près
équivalentes : « Pensée et calcul » et « Toute pensée est-elle un
calcul ? », « Être impossible » et « Qu'est-ce qu'être impossible ? », etc.

*** Un seul concept

Lorsque le sujet porte sur un seul concept, les problématiques les plus
fréquentes sont :

1. un problème de /définition/ ;

2. un problème d'/existence/ ;

3. la discussion d'une /thèse/ naturelle sur ce concept.

Par exemple, sur « Être impossible », on peut s'interroger sur la
/définition/, c'est-à-dire sur ce que c'est qu'être impossible : est-ce
la même chose qu'être contradictoire ? Et si oui, contradictoire avec
quoi : les lois logiques, les lois physiques, des lois métaphysiques ?
Sur « La substance », on peut s'interroger sur l'/existence/ des
substances en elles-mêmes, et non seulement dans notre pensée. Sur « La
spéculation », on peut discuter la /thèse/ assez naturelle et répandue
selon laquelle toute spéculation est nécessairement vaine et stérile.
Mais évidemment, on peut choisir d'autres problématiques pour chacun de
ces sujets : il n'existe pas une seule bonne problématique par sujet.

*** Deux concepts

Lorsqu'un sujet comporte deux termes (ou trois, comme « Ordre, nombre,
mesure »), il existe un piège à éviter à tout prix, qui est de traiter le
sujet concept par concept, comme Eltsine mangeait les hamburgers couche
par couche : par exemple, de traiter, pour « Genèse et structure »,
d'abord la genèse, ensuite la structure, enfin les relations entre
elles. Dans un tel traitement, seule la troisième partie serait dans le
sujet. Il faut traiter d'entrée de jeu les relations entre les deux
notions.

C'est en introduction, et plus précisément lors de l'analyse du sujet,
que l'on étudie chacune des notions pour elle-même : d'abord la genèse,
ensuite la structure. Mais la problématique doit déjà lier les deux
notions et poser le problème de leur articulation. Ensuite, chacune des
parties du développement doit porter sur la nature de cette relation.

De même, pour traiter le sujet « Mathématiques et philosophie », on ne
séparera pas les analyses sur les mathématiques de celles qui portent
sur la philosophie. Il faut d'emblée étudier, par exemple, si la
philosophie peut adopter une méthode mathématique comme dans l'/Éthique/
de Spinoza, et si certains concepts mathématiques --- nombre
irrationnel, nombre imaginaire, espace à $n$ dimensions etc. --- peuvent
posséder une signification philosophique ; c'est-à-dire, en somme,
quelle est la part de mathématiques dans la philosophie, et quelle est
la part de philosophie dans les mathématiques.

*** Une question

Les sujets qui se présentent sous la forme d'une question sont réputés
les plus faciles, mais il faut bien prendre garde à deux pièges :

-  que la nécessité de poser la question ait bien été expliquée en
   introduction : la question ne doit pas paraître arbitraire ;

-  que la problématique ne soit pas la simple paraphrase du sujet.

*** Une citation

Lorsque le sujet est une citation, il ne doit jamais être pris au pied
de la lettre. Quitte à jouer sur les mots, les deux sujets suivants
appellent bel et bien des traitements distincts :

-  « Pourquoi y a-t-il quelque chose plutôt que rien ? »

-  « ``Pourquoi y a-t-il quelque chose plutôt que rien ?'' »

Dans le premier cas, le sujet est une question, tandis que dans le
second il est une citation (de Leibniz). Quand le sujet est une
question, on doit y envisager des réponses (métaphysiques,
scientifiques, phénoménologiques...), et examiner si elles sont
satisfaisantes. Quand le sujet est une citation, on doit se demander ce
qui peut nous amener à poser cette question ; par exemple, quelle est la
spécificité de l'être humain pour qu'il puisse se poser cette question
--- la question contre-factuelle par excellence ?

De même, avec le sujet « « Tous pourris » », il est évidemment hors de
question de développer la thèse selon laquelle tous les hommes
politiques sont corrompus, puis de voir platement que tous les hommes
politiques ne sont peut-être pas corrompus ; mais il faut s'interroger
sur l'existence même de ce slogan, sur les intérêts de ceux qui le
proclament, sur le danger qu'il représente pour la démocratie.

Une citation ne doit donc jamais être prise au pied de la lettre. Elle
doit toujours susciter une interrogation de second degré, sur
l'existence et les conditions de possibilité du discours qu'elle
rapporte.
		
** Le plan

*** Annonce du plan 
L'annonce du plan est un sujet sensible entre correcteurs ; mais par
chance, chacun est tolérant avec le parti pris adverse, pourvu qu'il
soit habilement adopté.

Certains préconisent en effet d'annoncer dès l'introduction le plan
entier, ce qui confère une véritable unité à la dissertation, et montre
que l'étudiant sait dès le début où il va. De plus, cela facilite le
travail du correcteur en lui permettant de s'orienter facilement dans la
copie.

Mais on peut préférer ne pas « griller toutes ses cartouches » dès la
première page, et ménager un peu de suspens. Il est en effet toujours un
peu étrange d'annoncer la première partie, puis la deuxième, puis la
troisième, puis de revenir à la première pour la développer. À quoi bon,
si vous avez déjà tout dit ? Mais si vous n'annoncez pas le plan, il
faudra ensuite que les transitions soient irréprochables et
transparentes. Sinon, le correcteur aura du mal à comprendre la
structure de votre copie, et votre note en subira les conséquences.

Dans tous les cas, il faut annoncer au moins la première partie,
c'est-à-dire montrer comment la problématique mène naturellement à
envisager un premier point de vue :

#+BEGIN_QUOTE
  Nous verrons dans un premier temps que la diversité et
  l'imprévisibilité de l'activité spirituelle humaine présentent autant
  de résistances à toute réduction de la pensée au calcul.
#+END_QUOTE

En tout état de cause, il faut éviter à tout prix le lexique du
boucher : « nous allons traiter cette question en trois parties », ou,
pire, « nous allons examiner trois points de vue ». Tout au plus peut-on
annoncer que « notre réflexion connaîtra trois moments successifs » : on
doit insister sur la continuité de la pensée entre les différentes
parties du plan.

*** Quelques types de plan

Il existe un certain nombre de plans récurrents, que l'on peut appeler
plan dialectique, plan de réhabilitation, plan de dégradation, plan
criticiste, etc. Certains d'entre eux seront décrits ci-dessous. Mais il
faut bien se garder de vouloir appliquer un traitement mécanique aux
sujets. Appliqué à toute force à un sujet, un plan inapproprié gâchera
toute la dissertation. Ces quelques plans récurrents sont présentés
seulement à titre de suggestion, mais ce ne sont pas les seuls plans
possibles, et encore moins les meilleurs. Le meilleur plan sera toujours
celui que vous aurez inventé spécifiquement pour tel ou tel sujet.

**** Le plan dialectique

Le plan dialectique est réputé, à tort, le plus philosophique : à ses
élèves de l'École Normale Supérieure, Louis Althusser proclamait que
tout plan devait représenter d'abord la passion, ensuite la crucifixion,
enfin la résurrection. Le fameux plan par « thèse, antithèse, synthèse »
est effectivement pertinent dans certaines circonstances.

Par exemple, sur le sujet « La substance », on pourrait adopter le plan
dialectique suivant :

1. la substance comme /substrat/ : derrière tout phénomène doit se
   trouver une entité permanente, qui soit en même temps le support du
   discours (Aristote) ;

2. la substance comme /fiction/ : on n'a jamais d'expérience de la
   substance, mais seulement de ses manifestations (Berkeley, Hume) ;

3. la substance comme /fonction/ : la substance n'est certes jamais
   connue en elle-même, mais elle doit être pensée pour rendre possible
   une connaissance des phénomènes (Kant).

Le plan dialectique a pourtant ses inconvénients :

1. il est généralement le plan le plus attendu --- or ce qui ne surprend
   pas votre correcteur tend à l'ennuyer, surtout lorsque le même plan
   fade se voit reproduit en trente exemplaires ;

2. le désir de synthèse à tout prix engendre souvent une troisième
   partie extrêmement plate, sans saveur ni force, où l'on s'efforce de
   concilier sans combat la version amollie de thèses contradictoires.
   Souvent la deuxième partie, celle de la critique, est celle où l'on a
   pris le plus de plaisir, et dont la conciliation finale est un
   affaiblissement considérable.

Aussi convient-il parfois de sacrifier le plan dialectique à d'autres
types de plan, présentant plus de vigueur.

**** Le plan criticiste

Le plan criticiste, sous-espèce du plan dialectique, peut convenir pour
des sujets tels que « La substance », « Le moi », « La conscience
collective », « L'universel », « L'histoire a-t-elle un sens ? », etc. ---
typiquement, quand le sujet porte sur une notion transcendante mais
d'usage fréquent. Le plan est le suivant :

1. l'/existence/ de la chose ;

2. la chose n'est qu'une /illusion/ ;

3. on peut faire un /usage régulateur/ de la chose, c'est-à-dire
   postuler son existence à des fins théoriques ou pratiques, faire
   « comme si » la chose existait.

Ainsi, on peut adopter le plan criticiste pour le sujet « L'histoire
a-t-elle un sens ? » :

1. il /existe/ un sens de l'histoire : on constate en observant
   l'histoire un progrès vers l'égalité et la démocratie ;

2. le sens de l'histoire comme /illusion/ : l'histoire est faite de
   contingences, et ce sont les vainqueurs qui réinventent l'histoire à
   leur avantage ;

3. le sens de l'histoire comme /postulat/ : poser l'existence d'un sens
   de l'histoire peut servir de guide à notre action, par exemple pour
   fixer des fins à l'action politique. Cela ne signifie pas que
   l'histoire ait un sens en elle-même, mais si nous décidons d'agir
   « comme si » c'était le cas, alors par nos actes elle acquerra bien un
   sens.

Naturellement, il faut toujours déterminer avec précision à quel intérêt
est soumis le « comme si » : intérêt théorique (connaître le monde),
pratique (progrès moral), etc.

**** Le plan de réhabilitation

Il arrive qu'un sujet de dissertation corresponde à un concept chargé
d'une forte connotation péjorative : « L'égoïsme », « L'erreur », « Le
mauvais goût », « L'argument d'autorité », « Les causes finales »,
« L'anachronisme », etc. Un plan dialectique pourrait être ici extrêmement
fade :

1. dans une première partie, on /critique/ le concept, selon la
   conception commune (l'égoïsme est un intérêt immoral et nuisible à la
   société, l'erreur fait obstacle à la connaissance, le mauvais goût
   est une perversion du goût) ;

2. dans une deuxième partie, on /justifie/ ces concepts (l'égoïsme est
   l'intérêt dominant chez l'homme ; l'erreur est parfois fertile ; le
   mauvais goût peut revêtir un intérêt esthétique, par exemple dans le
   kitsch ou chez Warhol) ;

3. dans une troisième partie, on /concilie/ avec fadeur les deux points
   de vue précédents (l'égoïsme est parfois bon, mais il ne faut pas en
   abuser ; l'erreur est parfois fertile, mais il faut quand même faire
   attention ; le mauvais goût ne doit quand même pas être excessif).

Naturellement, on peut utiliser le plan dialectique de manière plus
fine, y compris avec ces sujets ; mais, mal utilisé, il revient souvent
à ces formes sans force.

Un plan plus puissant est alors le suivant, qui procède à une
/réhabilitation/ progressive du concept péjoratif :

1. le concept est /nuisible/ (l'égoïsme est un intérêt immoral et
   nuisible à la société, l'erreur fait obstacle à la connaissance, le
   mauvais goût est une perversion du goût) ;

2. le concept est /inévitable/ (toute action a lieu sur fond d'égoïsme,
   toute connaissance repose sur une erreur, tout goût est mauvais) ;

3. le concept est même parfois /bénéfique/ ou souhaitable (l'égoïsme a
   des effets profitables, l'erreur fait progresser la connaissance, le
   mauvais goût fait évoluer l'histoire de l'art).

Dans ce dernier plan, il ne s'agit pas d'adopter une thèse conciliant
deux points de vue opposés, mais au contraire d'approfondir
progressivement une thèse forte, selon une véritable montée en
puissance.

Naturellement, le plan de réhabilitation est difficilement justifiable
dans certains cas : « L'esclavage », « Le terrorisme », « Le racisme ». Ici,
toute idée de réhabilitation serait assez scabreuse.

**** Le plan de dégradation

Symétriquement au précédent, le plan peut consister à dégrader un
concept spontanément perçu comme positif : « Le désintéressement », « La
sympathie », « La vérité », « La sincérité », « Le bon goût », « L'égalité »...
On montre alors successivement :

1. que le concept est /bénéfique/ ;

2. qu'il est /impossible/ ;

3. qu'il est même parfois /nuisible/.

**** Le plan /ad hoc/

Il existe un nombre indéfini de plans /ad hoc/, parfaitement adaptés à
un sujet, et souvent à un seul, et qui seront bien plus pertinents que
tous les plans génériques --- dialectique, réhabilitation, dégradation,
criticiste --- dont vous aurez entendu parler. Ce plan est, à chaque
fois, à inventer pour la première fois. S'il demande de l'audace, il est
souvent bien plus payant que tous les autres types de plans.



* Développement

** Structure du développement

*** Nombre de parties

Le développement est typiquement constitué de /deux à quatre parties/.
Avec une seule partie, on reprocherait à l'étudiant de n'avoir développé
d'un point de vue unilatéral ; avec cinq, de n'avoir pas suffisamment su
regrouper ses pensées. Trois parties est certes le nombre canonique,
mais une excellente dissertation peut n'en comporter que deux, pour peu
qu'elle n'ait rien manqué d'essentiel. Rien n'est pire qu'une troisième
partie boiteuse, rajoutée à la hâte pour atteindre le chiffre magique,
et où l'étudiant n'a plus rien d'essentiel à ajouter.

*** Chaque partie est une réponse à la problématique

Chaque partie doit apporter une proposition de réponse à la
problématique. En particulier, il ne faut surtout pas consacrer la
première partie à redéfinir les termes du sujet --- ce qui aurait dû
être fait en introduction --- ou à exposer une thèse qui ne serait que
préalable à la réponse.

Sur votre brouillon, le titre de chaque partie doit répondre
explicitement à la question qu'est la problématique. Dans la copie, les
premières phrases de chaque partie doivent formuler clairement la thèse
soutenue. Elles peuvent ensuite indiquer brièvement le plan de la
partie, c'est-à-dire annoncer les sous-parties qui la composent.

*** Sous-parties

Chaque partie doit être divisée en /sous-parties/. Ici encore, le nombre
moyen est trois, mais deux ou quatre peuvent tout à fait convenir si la
matière l'exige. Chaque sous-partie doit être un élément de réponse à la
problématique. La première phrase de la sous-partie doit dire clairement
la thèse qui sera soutenue. Ensuite vient l'argumentation. Enfin, la
dernière phrase résume la thèse de la sous-partie et montre ce qu'elle
apporte à l'argumentation de la partie dans laquelle nous nous trouvons.

On ne saute pas de lignes à l'intérieur d'une partie. On se contente
d'aller à la ligne à chaque nouvelle sous-partie.

*** Composition du développement

Le plan du développement est donc le suivant :

- quelques lignes blanches après l'introduction ;
- un court alinéa pour énoncer la thèse de la première partie (de deux à
  cinq lignes), et éventuellement annoncer le plan des sous-parties ;
- l'alinéa correspondant à la première sous-partie de la première partie :
  + une phrase pour énoncer la thèse de la sous-partie ;
  + l'argumentation (raisonnement, exemple, références
    philosophiques...) en faveur de cette thèse ;
  + une phrase pour résumer la thèse démontrée dans cette sous-partie ;
- l'alinéa correspondant à la deuxième sous-partie de la première
  partie ;
- etc. jusqu'à la dernière sous-partie de la première partie ;
- un alinéa (collé au précédent) pour la transition ;
- quelques lignes blanches avant la deuxième partie.

** Quelles thèses peut-on soutenir ?

*** La qualité de l'argumentation comme seul juge

Les candidats doivent comprendre qu'ils ne sont jamais jugés sur leurs
idées. Le correcteur n'attend pas des copies qu'il lit la confirmation
de ses propres convictions philosophiques. Il veut lire des copies
argumentées. On préfère largement une copie défendant bien une thèse
avec laquelle on n'est pas d'accord à une copie défendant mal une thèse
qui a notre sympathie. N'essayez donc pas de deviner les orientations
philosophiques du correcteur, qui est souvent plus ouvert d'esprit que
vous ne le croyez. Les inspirations kantienne, heideggerienne,
wittgensteinienne, quinienne ne sont ni encouragées, ni bannies : tout
dépend de la manière dont vous argumenterez vos idées.

*** Défendre des thèses non triviales

Voici deux conseils généraux au sujet des thèses que vous défendrez :
défendez des thèses non triviales, mais ne cherchez pas l'originalité à
tout prix.

On est souvent conduit, en début de copie notamment, à défendre des
thèses triviales, proches du sens commun : dire que le mal existe, que
la substance existe, etc. Mais /cela ne doit pas dépasser le début de la
première partie/. Il faut rapidement passer à des considérations non
triviales. Cela peut se faire notamment de deux manières : soit en
rompant avec ces apparences, et en montrant que les choses sont en
réalité plus compliquées, que le sens commun est illusoire ; soit en
examinant de manière structurée tous les présupposés de ce point de vue
trivial, en reconstruisant en quelque sorte le « système implicite » du
sens commun. Dans les deux cas, il ne faut /surtout pas s'attarder à la
surface des choses/ (quitte à y revenir plus tard, de manière justement
non triviale) : c'est ce qui fait toute la différence entre la
dissertation de philosophie et la dissertation de culture générale.

*** Décrire le sens commun comme le système d'un philosophe

On a parfois du mal à remplir la première partie d'une dissertation.
Comme elle décrit généralement le point de vue du sens commun, il est
difficile d'y trouver de la profondeur. Par exemple, pour un sujet comme
« Le monde extérieur existe-t-il ? », comment peut-on consacrer plus de
deux lignes à dire que, dans la vie de tous les jours, nous considérons
l'existence du monde extérieur comme allant de soi ?

Pour remédier à ce problème, la plus-value que vous apporterez dans la
première partie ne sera pas du contenu, mais de la /structure/. Par
exemple, vous pouvez, dans chacune des trois ou quatre sous-parties de
cette première partie, mettre au jour l'une des raisons que nous avons
de croire à l'existence du monde extérieur : l'impression de résistance
(le monde ne se comporte pas toujours comme je l'attends ou le désire),
l'existence d'une intersubjectivité (nos rapports avec autrui supposent
un monde commun), l'efficacité pratique de cette croyance... Vous pouvez
ainsi reconstruire le « système implicite » du sens commun, le décrire
comme s'il s'agissait de la pensée d'un philosophe. La structure que
vous aurez ainsi dégagée pourra d'ailleurs vous être très utile en
deuxième partie : vous pourrez alors démonter, argument par argument,
toutes les bonnes raisons que nous avons de croire à l'existence du
monde extérieur.

Si vous défendez une thèse non triviale, il vous viendra souvent à
l'esprit, au moment de l'écrire sur la copie, une objection naïve. Dans
ce cas, /écartez-la explicitement/, pour prévenir tout malentendu et
montrer que vous anticipez le sens commun et prétendez montrer quelque
chose de plus ambitieux.

*** Éviter l'originalité pour l'originalité

Mais il faut prendre garde également à l'originalité à tout prix. Les
dissertations, surtout en dernière partie, sont parfois le prétexte à
des envolées d'enthousiasme, où le candidat défend des thèses abstraites
dont le principal intérêt est de n'avoir prétendument jamais été
entendues. Le correcteur n'a généralement aucune objection de principe à
cela, à condition que les thèses soient argumentées : la nouveauté n'a
pas valeur d'argument.

Il faut donc prendre garde à défendre des thèses non triviales, et à les
argumenter. Ce sont les seuls impératifs concernant le contenu de vos
thèses ; sous ces seules réserves, qui sont naturelles, votre liberté
est totale.

** Comment soutenir une thèse

Toute thèse doit être /soutenue/, et jamais simplement exposée.

Il n'existe que deux moyens de soutenir une thèse : soit, /a priori/, en
la fondant sur des principes ; soit, /a posteriori/, en l'appuyant sur
des exemples. Dans les deux cas, il convient d'éviter toute
/généralisation abusive/.

*** Preuves /a priori/ : les arguments

Supposons que, dans le cadre d'une dissertation sur le thème « Le
désintéressement », on veuille --- provisoirement ou non --- répondre par
que le désintéressement absolu n'existe pas, c'est-à-dire que toutes nos
actions sont fondamentalement intéressées. Une preuve /a priori/
pourrait être la suivante :

#+BEGIN_QUOTE
  L'homme est un être vivant ; or, un être vivant ne peut être poussé à
  agir d'une manière déterminée que s'il y est poussé par un intérêt ;
  par conséquent, l'homme est principalement motivé par des intérêts, et
  non par des valeurs morales.
#+END_QUOTE

Matériellement, les prémisses de cet argument sont certes contestables :
il faut avoir préalablement montré que l'intérêt et la valeur sont
mutuellement exclusifs, et que l'homme est un être vivant exactement au
même titre que les animaux ; mais l'essentiel, de notre point de vue
actuel, réside dans le caractère /a priori/ de l'argument. Celui-ci est
un syllogisme formellement valide [5].

*** Preuves /a posteriori/ : les exemples

**** Importance des exemples 

Les exemples jouent un rôle crucial dans une dissertation. Ils montrent
d'une part que vous possédez une connaissance directe des objets sur
lesquels vous raisonnez, et d'autre part que vous êtes capables de
relier vos thèses philosophiques à des remarques de premier niveau. Dans
une dissertation de philosophie politique, citez des événements
historiques appartenant à des époques variées. Dans une dissertation
d'esthétique, citez des œuvres d'art relevant d'époques et de genres
variés. Dans une dissertation d'épistémologie, donnez des exemples
scientifiques. Dans une dissertation de morale, de philosophie du
langage etc., donnez toujours des exemples concrets. Utiliser des
exemples concrets, c'est montrer que vos thèses se vérifient à même les
choses, et qu'elles ne sont pas séparées du réel qu'elles prétendent
décrire.

La manipulation d'exemples doit donc faire l'objet d'un soin
particulier. Mais il faut pour cela être lucide sur l'apport réel de nos
exemples à l'argumentation : éviter les généralisations abusives, et
savoir bien user des exemples.

**** Le danger de la généralisation abusive
   
   Une preuve /a posteriori/ de la même thèse ne peut être simplement de la
   forme suivante :
   
   #+BEGIN_QUOTE
   Un rapide coup d'œil sur l'histoire de l'humanité suffit à nous
   convaincre de la méchanceté originelle de l'homme.
   #+END_QUOTE
   
   La preuve n'est pas convaincante, car de ce qu'il ait existé
   /certains/ hommes mauvais --- on n'aura effectivement guère de peine
   à en trouver --- elle conclut que /tous/ les hommes sont mauvais. En
   termes logiques, le sophisme repose sur une confusion entre
   quantificateurs. La généralisation est abusive.

**** Le bon usage des exemples
   
   D'où le problème suivant : comment peut-on avancer la moindre thèse
   /a posteriori/ qui soit en même temps générale, si l'expérience ne
   nous livre jamais que du particulier ? Un procédé pourra vous y
   aider : l'/exemple-limite/.
   
   On peut en effet distinguer trois types d'exemples : l'exemple
   typique, l'exemple ordinaire et l'exemple-limite. L'exemple typique
   est celui qui a été choisi avec soin comme illustrant avec une
   facilité particulière la thèse que l'on veut défendre. Arguer de
   Staline pour affirmer que tous les hommes sont mauvais, c'est se
   faciliter outrageusement la tâche ; l'argument n'a strictement aucune
   valeur. On peut tout au plus y recourir provisoirement, dans une
   première approche, en montrant que l'on utilise consciemment un
   exemple typique, et surtout /en l'accompagnant d'une analyse
   détaillée/ : « l'exemple de Staline est à cet égard tout à fait
   caractéristique (ou représentatif), car... ». Pour compenser la
   facilité de l'exemple, qui joue d'abord en votre défaveur,
   l'examinateur attendra que vous en ayez une connaissance
   approfondie ; vous montrerez donc bien en quoi la constitution
   interne de votre exemple illustre votre thèse de manière non
   triviale.
   
   L'exemple ordinaire est celui qui puise dans la moyenne des individus
   pour montrer la validité de la thèse : on montrera par exemple
   comment l'homme est mauvais au quotidien. La force persuasive est
   certes plus grande que pour l'exemple typique, mais non encore
   absolue, car il peut exister des personnes exceptionnelles, largement
   supérieures à l'homme ordinaire. Comme le précédent, cet argument
   serait une généralisation abusive, c'est-à-dire une confusion entre
   quantificateurs : « il existe des hommes intéressés, donc tous les
   hommes sont intéressés ».
   
   Mais montrer que Pierre ou Jean sont mauvais a beaucoup moins de
   force que de montrer en quoi Gandhi pouvait être quelqu'un de
   fondamentalement intéressé. Parmi les exemples, seul
   l'exemple-limite, montrant que même les actions de Gandhi peuvent
   être justifiées par un intérêt personnel, a donc une réelle valeur
   argumentative. Soutenir une hypothèse par des exemples n'a de valeur
   que comme « une vérification de cette hypothèse sur des cas
   exemplaires, délibérément choisis comme particulièrement défavorables
   à sa démonstration [6] ».

*** La modalité des thèses

Un sophisme apparaît régulièrement dans les dissertations : il consiste
à évoquer la simple possibilité d'une thèse, et, de là, à en conclure la
vérité ou la nécessité. De même que la généralisation abusive était une
confusion entre quantificateurs (« il existe des hommes intéressés, donc
tous les hommes sont intéressés »), on peut voir ici une confusion entre
modalisateurs : « il est possible que tous les hommes soient intéressés,
donc tous les hommes sont intéressés ».

Il faut donc prendre garde aux modalisateurs que l'on emploie, et
principalement à ne pas considérer comme avérées des thèses dont on
s'est contenté d'évoquer la possibilité. Assurément, certaines thèses,
notamment dans les philosophies du soupçon comme celle de Nietzsche,
sont condamnées à rester dans le domaine du possible, et sont
difficilement prouvables : comment prouver en toute généralité que la
nature tout entière est régie par la volonté de puissance ? Nietzsche
lui-même ne le démontre pas, se contentant d'exposer cette thèse [7].
Mais parfois la simple possibilité est suffisante, car elle permet de
réfuter la prétention adverse à la nécessité (« le caractère nécessaire
de l'existence d'actions désintéressées est remis en cause par la seule
cohérence de l'hypothèse d'un monde régi par la volonté de puissance »).
Dans tous les cas, une modalité modeste mais légitime a toujours plus de
force qu'une modalité ambitieuse mais usurpée.

** Comment réfuter une thèse

Il existe au moins quatre façons de réfuter une thèse : la première est
/a posteriori/, les trois autres /a priori/.

Une première façon de réfuter une thèse est de /produire un
contre-exemple/. Si quelqu'un soutient la thèse « il n'y a pas d'action
désintéressée », inutile de montrer que /toute/ action est
désintéressée ! Il suffit d'exhiber un seul contre-exemple pour la
réfuter complètement.

Une deuxième façon est de montrer une /faille dans le raisonnement
adverse/. Supposons quelqu'un soutienne la thèse « il n'y a pas d'action
désintéressée » en commettant, comme il arrive souvent, une erreur de
quantificateur (« il n'existe pas d'action désintéressée, puisque nous
voyons sans cesse les hommes autour de nous agir selon leur intérêt ») ou
une erreur de modalisateur (« il n'existe pas d'action désintéressée,
puisqu'il est possible que tout homme ne soit mû que par son intérêt
personnel »). Dans ce cas, montrez explicitement quelle est la faille, et
vous aurez réfuté la démonstration (reste à démontrer la thèse inverse).

Une troisième façon est d'/attaquer les prémisses/ ou les présupposés du
raisonnement adverse. Supposons que quelqu'un nie l'existence d'actions
désintéressées en s'appuyant sur un syllogisme valide : « L'homme est un
être vivant ; or, un être vivant ne peut être poussé à agir d'une
manière déterminée que s'il y est poussé par un intérêt ; par
conséquent, l'homme est principalement motivé par des intérêts, et non
par des valeurs morales ». Vous pouvez réfuter cette argumentation en
rejetant l'une des prémisses -- par exemple en disant que l'homme ne se
réduit précisément pas à son animalité (ou du moins /pas
nécessairement/, ce qui suffit à invalider la conclusion du syllogisme).

Une quatrième façon est de /critiquer les définitions/ des termes. Si
quelqu'un soutient qu'il n'y a pas d'action désintéressée, vous pouvez
critiquer cette thèse en disant qu'elle confond différentes sortes
d'intérêt, qu'il faut en réalité distinguer : par exemple l'intérêt
personnel, l'intérêt collectif, l'intérêt rationnel...

** Comment mobiliser l'histoire de la philosophie

*** Reconstruire le discours des philosophes

Un philosophe doit toujours être introduit, et savoir s'effacer au bon
moment. Il n'est qu'invité dans votre dissertation ; tout soliste doit
rester aux ordres du chef d'orchestre. En termes concrets, la première
phrase d'un alinéa, où l'on annonce la thèse à venir, et la dernière, où
l'on résume la thèse examinée, doivent être anonymées comme des copies
d'examen, c'est-à-dire ne contenir aucun nom de philosophe.

Par ailleurs, un philosophe n'est ni un totem, ni un tabou. Une sottise,
même énoncée par Kant, reste une sottise [8] : un grand nom n'est jamais
une autorité. Aussi toute assertion, même reprise de Kant, doit-elle
être fondée au même titre que si c'était la vôtre. Une thèse n'est en
effet jamais isolée dans l'œuvre d'un philosophe : en ceci, elle est
toujours plus qu'une simple citation. Elle s'inscrit dans un système, ou
plus modestement dans un ensemble de raisons, et c'est sur lui qu'il
faut la fonder.

*** Les citations sont facultatives

Pour cette raison, une citation, à elle seule, est rarement éclairante.
Elle doit être décortiquée, expliquée, justifiée. Une copie sans
citation, dans laquelle toutes les thèses sont justifiées les unes par
les autres, est largement préférable à un agrégat de citations supposées
transparentes et autosuffisantes. Rien ne saurait donc être plus
nuisible à une dissertation philosophique que le /Dictionnaire de
citations/, catalogue d'aphorismes certes rhétoriquement habiles, mais
dont la profondeur n'est souvent qu'apparente, et la systématicité
toujours absente.

Un philosophe doit toujours être cité avec la plus grande précision
possible. Il ne suffit pas de dire que Kant a affirmé quelque part
l'existence de connaissances synthétiques /a priori/ : il faut au moins
renvoyer à la /Critique de la raison pure/, voire plus précisément à son
Introduction.

On peut mentionner quelques citations si on a le bonheur de les
connaître par cœur. Mais si l'on a peu de mémoire, un résumé fidèle des
thèses d'un philosophe n'a pas moins de valeur. En outre, les citations
ont souvent un effet pervers : pour compenser l'effort qu'a nécessité
leur apprentissage, on tend à les mobiliser à tort et à travers ou à en
faire un usage purement décoratif. L'essentiel est, à l'inverse, de
reconstruire explicitement le raisonnement qui fonde l'auteur cité à
énoncer cette formule.

** Transitions

Les transitions ne sont pas une simple exigence rhétorique, mais
obéissent à une véritable nécessité conceptuelle. Elles témoignent en
effet d'une véritable continuité entre les pensées, plutôt que d'une
simple juxtaposition. Une transition procède typiquement en trois
moments :

1. /résumer/ en une seule phrase la thèse que l'on vient d'exposer ;

2. montrer de manière détaillée, et surtout pas de manière symbolique ou
   allusive, ce qui /manque/ à cette thèse ;

3. soumettre l'/ébauche/ d'une solution, telle qu'elle sera développée
   dans la partie ou la sous-partie suivante.

Chacun de ces trois moments est crucial, mais c'est souvent le second
qui fait défaut : on change de point de vue sans avoir vraiment montré
pourquoi il était /absolument nécessaire/ (et non simplement possible)
de le faire. Si on ne montre pas clairement dans la transition pourquoi
le point de vue adopté jusqu'ici est insatisfaisant et doit être
abandonné, le lecteur n'a strictement aucune raison de lire la partie
suivante.

Où doit-on mettre des transitions ?

1. à la fin de chaque sous-partie, dans le même alinéa ;

2. à la fin de chaque partie, ce qui mérite souvent un alinéa à part ;
   et ce n'est pas être verbeux que de lui consacrer cinq à dix lignes,
   ou plus.

Par exemple, supposons que nous ayons adopté le plan suivant pour le
sujet « La guerre » :

1. la guerre est un /déchaînement de violence/ ;

2. la guerre est une violence, mais dirigée par l'intellect : une
   /violence rationnelle/ ;

3. la pertinence de la guerre dépend des valeurs qui la motivent : sous
   certaines conditions, elle peut devenir une /violence raisonnable/.

La transition de la première à la deuxième partie peut être l'alinéa
suivant :

#+BEGIN_QUOTE
  Nous avons vu que la guerre pouvait se présenter au premier abord
  comme un déchaînement de violence, s'inscrivant dans la continuité de
  la rivalité entre les individus pour satisfaire leurs besoins naturels
  (boire, manger, respirer...). Mais ce serait méconnaître trois
  distinctions essentielles. D'abord, les belligérants ne sont pas des
  individus, mais des entités plus abstraites et plus larges, à savoir
  des États. Ensuite, les motivations d'une guerre sont rarement
  réductibles aux conditions de la satisfaction des besoins naturels :
  on entre en guerre pour s'assurer une position économique privilégiée,
  pour acquérir des terres riches en minerais, pour faire coïncider les
  frontiètres politiques de l'« État » avec les frontières culturelles de
  la « nation », pour laver l'humiliation d'une guerre passée, pour
  répandre la liberté révolutionnaire dans le monde entier, pour
  réaliser le communisme international, pour agrandir son « espace
  vital », pour recouvrer la terre de ses ancêtres, etc. : rien n'animal
  dans toutes ces motivations. Enfin, les moyens d'action sont de plus
  en plus « raffinés » : loin de la pierre que l'on jette à autrui, on
  fait de plus en plus appel aux dernières avancées scientifiques (armes
  à feu, bombes atomiques, armes chimiques ou bactériologiques). Loin
  d'être un pur et simple déchaînement de violence, la guerre se
  caractérise donc par un appel constant à l'intelligence. Ne faut-il
  pas, dès lors, considérer que la rationalité est aussi essentielle à
  la guerre que la violence ?
#+END_QUOTE

Lorsque l'on adopte un plan dialectique, l'une des transitions doit être
plus soignée encore que toutes les autres : celle qui conclut la
deuxième partie et annonce la troisième. Ici, plus de quinze lignes sont
rarement un luxe. Il faut prendre le temps de bien montrer toute la
tension à laquelle on est parvenu, dans sa radicalité. Plus la
contradiction est radicale, plus la résolution est attendue avec
impatience : il faut savoir susciter l'intérêt du correcteur !

* Conclusion

** Une réponse explicite

Le rôle de la conclusion est simple : elle doit /répondre à la
problématique/. Une conclusion ne doit donc pas être simplement un
résumé de la dissertation, encore moins être une table des matières,
mais répondre explicitement à la question dont elle était partie.

Il faut fuir comme la peste les conclusions sceptiques paresseuses,
comme « on a vu qu'il existait beaucoup de réponses différentes à cette
question » ou « on a vu que cette notion est complexe et comporte de
nombreux aspects ». On peut certes conclure sur une impossibilité de
trancher, mais elle doit être argumentée, et non s'appuyer sur la seule
diversité des opinions. La diversité des opinions n'est plus un bon
point d'arrivée de dissertation qu'un bon point de départ.

La conclusion ne doit contenir /aucun nom de philosophe/. C'est vous qui
parlez en votre nom. Ne dites donc jamais : « en adoptant un point de vue
heideggerien, on peut dire que... ». Si vous avez adopté le point de vue
de Heidegger en citant cet auteur à la fin de votre dernière partie, il
est temps maintenant de voler de vos propres ailes ; vous n'avez plus
besoin de Heidegger pour porter les idées que vous vous êtes
appropriées.

** L'ouverture du sujet

Si vous êtes partis d'une amorce, la reprendre en conclusion pour
l'éclairer d'un jour nouveau peut être instructif ; bien manipulé, ce
procédé confère à la dissertation une efficacité qui n'est pas seulement
rhétorique, mais également spéculative : il montre que vous saviez dès
le départ où vous alliez, et que le cheminement n'a pas été improvisé
ligne après ligne.

Par exemple, sur le sujet « La guerre », on peut faire écho en conclusion
à l'amorce qui comparait Jaurès et Cavaillès :

#+BEGIN_QUOTE
  Si le pacifiste Jaurès et le résistant Cavaillès peuvent être tous
  deux considérés comme des justes, c'est que l'opposition formelle de
  la guerre et de la paix n'est pas tenable, sans quoi Jaurès serait
  lâche ou Cavaillès militariste. Il nous faut donc distinguer deux
  sortes de guerres, correspondant à deux sortes de paix. Si Jaurès
  était pacifiste, ce n'était pas par simple refus de la guerre (la paix
  comme absence de guerre, ou /paix négative/), mais au nom d'une /paix
  positive/ conçue comme entente entre les peuples. Si Cavaillès
  s'engagea dans la Résistance après l'Armistice, ce n'était pas par
  refus belliciste de l'état de paix, mais au nom d'une paix positive
  --- son avènement dût-il passer par la guerre --- et contre la paix
  négative s'accommodant de l'Occupation et des crimes dont elle fut le
  théâtre. En distinguant ces deux sortes de paix, on peut concevoir la
  proximité de ces deux personnes, qui est d'avoir subordonné le
  problème de la /valeur/ de la guerre prise absolument à celui de sa
  /pertinence/ dans une situation historique précise. Si l'on peut
  parler de « justes », c'est parce qu'ils ne pensèrent pas en opposant
  simplement guerre et paix, mais guerre injuste et paix juste pour
  Jaurès, guerre juste et paix injuste pour Cavaillès.
#+END_QUOTE

On préconise parfois le recours à l'/ouverture du sujet/. Mais, mal
maîtrisé, le procédé revient trop souvent à aborder soit des problèmes
qui n'ont aucun rapport avec le sujet (« car, après tout, qu'est-ce que
la vérité ?... »), soit des problèmes qui auraient dû être traités
(« une nouvelle question se pose, qui serait celle des valeurs au nom
desquelles on mène une guerre »). Dans le doute, il vaut mieux éviter ce
procédé, et terminer directement par la réponse à la question : ici
encore, la sobriété est parfois gage d'efficacité.

* Comment les correcteurs lisent les copies

Savoir sur quels critères vous êtes évalué vous permettra de rédiger des
copies satisfaisant le mieux possibles les attentes du correcteur.

** Ordre de lecture

Voici un exemple de lecture de copie. Le correcteur lit d'abord
l'introduction et la conclusion. À ce stade, il a souvent une idée de la
note à quatre points près. C'est comme s'il raisonnait par grandes
cases :

-  une case A pour les très bonnes copies, de 14 à 20 ;

-  une case B pour les copies correctes, de 10 à 14 ;

-  une case C pour les copies insatisfaisantes, de 6 à 10 ;

-  une case D pour les copies inachevées ou bâclées, en dessous de 6.

Ayant ainsi provisoirement identifié le profil de la copie, le
correcteur lit le développement, pour voir si les thèses sont
correctement argumentées : il juge la qualité de la démonstration, la
pertinence des exemples et des références philosophiques. Généralement,
le développement ne fera pas changer la copie de case --- du moins, pas
dans un sens favorable au candidat : une copie qui commence et qui finit
mal contient rarement un développement éblouissant. Le développement
permet surtout au correcteur de savoir où positionner la copie dans la
case qui lui correspond (A$+$, A$-$, B$+$, B$-$, ...) ; il permet donc
au candidat de gagner jusqu'à quatre points.

** Critères d'évaluation

Voici, dans l'ordre, les questions que le correcteur peut se poser.

1. Je lis l'introduction.

   -  Les principaux termes du sujet ont-ils été définis, au moins de
      façon provisoire ?

   -  Le sujet est-il bien problématisé, en partant de la construction
      d'une véritable tension ?

   -  Chacune des parties annoncées répond-elle à la problématique ?

   L'introduction permet déjà de savoir si le candidat s'est approprié
   le sujet pour le penser de façon personnelle.

2. Je lis la conclusion.

   -  La copie est-elle achevée ?

   -  La conclusion répond-elle clairement à la question posée dans
      l'introduction ?

   -  La conclusion est-elle intéressante, c'est-à-dire non triviale ?

3. Je lis le développement.

   -  La réflexion de chaque partie est-elle structurée en sous-parties,
      dont chacune contient une thèse ?

   -  Chaque thèse est-elle soutenue par une démonstration, ou par un
      exemple suffisamment analysé ?

   -  Le candidat mentionne-t-il les doctrines philosophiques de manière
      détaillée, en évitant l'avalanche de références évoquées de
      manière allusive ?

   -  Les transitions sont-elles pertinentes ?

* Sujets de dissertation

Voici des sujets pour s'entraîner à la dissertation[fn:1]. Pour vous
entraîner, il suffit de rédiger :

1. une introduction : définitions, tension, problématique ;

2. un plan détaillé (aucun nom de philosophe ne doit apparaître dans les
   titres des parties et sous-parties) ;

3. une courte conclusion répondant clairement à la problématique.

\begin{multicols}{2}
\noindent Peut-on renoncer à comprendre ? \par
\noindent Y a-t-il une éducation du goût ? \par
\noindent L'extraordinaire \par
\noindent Qu'est-ce qu'un monstre ? \par
\noindent A qui devons-nous obéir ? \par
\noindent Peut-on échapper au temps ? \par
\noindent Pourquoi se divertir ? \par
\noindent Y a-t-il de l'impensable ? \par
\noindent Le possible \par
\noindent Qu'est-ce qu'une expérience? \par
\noindent Y a-t-il des limites à la conscience ? \par
\noindent La chance \par
\noindent L'incertitude \par
\noindent Qu'est-ce qu'être efficace en politique ? \par
\noindent Tout est-il politique ? \par
\noindent L'universel \par
\noindent Ai-je un corps ? \par
\noindent Ignorer \par
\noindent La métaphysique est-elle une science ? \par
\noindent Que nous apprennent les mythes ? \par
\noindent Qu'est-ce que traduire ? \par
\noindent Le désir de savoir est-il naturel ? \par
\noindent L'insurrection est-elle un droit ? \par
\noindent Y a-t-il des leçons de l'histoire ? \par
\noindent L'égalité est-elle une condition de la liberté ? \par
\noindent Le passé \par
\noindent La connaissance de soi \par
\noindent L'objet de l'amour \par
\noindent Pourquoi raconter des histoires ? \par
\noindent L'amour-propre \par
\noindent Qui suis-je ? \par
\noindent Existe-t-il un art de penser ? \par
\noindent La mort de Dieu \par
\noindent Connaître l'infini \par
\noindent L'homme est-il un loup pour l'homme ? \par
\noindent L'œuvre d'art doit-elle nous émouvoir ? \par
\noindent La vérité en art \par
\noindent Vérité et certitude \par
\noindent L'enfant et l'adulte \par
\noindent Les animaux pensent-ils ? \par
\noindent Le beau a-t-il une histoire ? \par
\noindent L'éternité \par
\noindent L'interprétation \par
\noindent Peut-on penser sans concept ? \par
\noindent Entendre raison \par
\noindent Qu'est-ce que faire preuve d'humanité ? \par
\noindent L'histoire a-t-elle un sens ? \par
\noindent L'aveu \par
\noindent Prévoir \par
\noindent Que recherche l'artiste ? \par
\noindent Peut-on rester sceptique ? \par
\noindent L'outil \par
\noindent Le vrai et le faux \par
\noindent Faut-il une théorie de la connaissance ? \par
\noindent L’acte et l’œuvre \par
\noindent Qu’est-ce qu'un réfutation ? \par
\noindent L’exception \par
\noindent Le bavardage \par
\noindent La philosophie est-elle abstraite ? \par
\noindent L’éternité \par
\noindent L’homme est-il raisonnable par nature ? \par
\noindent Peut-on tout dire ? \par
\noindent Y a-t-il des actes de pensée ? \par
\noindent Tuer le temps \par
\noindent L’imprévisible \par
\noindent Qu’y a-t-il ? \par
\noindent Qu’est-ce qu’un accident ? \par
\noindent L’opinion \par
\noindent La gauche et la droite \par
\noindent Le privé et le public \par
\noindent Peut-on tout démontrer ? \par
\noindent Quel est l’objet de l’histoire ? \par
\noindent La cohérence \par
\noindent Que nul n’entre ici s’il n’est géomètre. \par
\noindent Histoire et géographie \par
\noindent Voir \par
\noindent La conscience a-t-elle des moments ? \par
\noindent L’argument d’autorité. \par
\noindent La désobéissance \par
\noindent Rêvons-nous ? \par
\noindent L’inhumain \par
\noindent Qu’est-ce qu’un principe ? \par
\noindent Y a-t-il une langue de la philosophie ? \par
\noindent L’introspection est-elle une connaissance ? \par
\noindent L’homme est-il un animal comme les autres ? \par
\noindent La nature est-elle bien faite ? \par
\noindent L’ordre. \par
\noindent La démocratie \par
\noindent Peut-on penser sans ordre ? \par
\noindent Qu’est-ce qu’un monstre ? \par
\noindent Le temps existe-t-il ? \par
\noindent Qu’est-ce qu’un auteur ? \par
\noindent Qu’est-ce qu’être ? \par
\noindent Peut-on être sceptique ? \par
\noindent Qu’est-ce qu’interpréter ? \par
\noindent Qu’est-ce qu’un peuple ? \par
\noindent Peut-on séparer l’homme et l’œuvre ? \par
\noindent Peut-on ne pas être soi-même ? \par
\noindent À quoi reconnaît-on une œuvre d’art ? \par
\noindent La haine de la raison \par
\noindent Comment penser le mouvement ? \par
\noindent Y a-t-il des régressions historiques ? \par
\noindent Suis-je seul au monde ? \par
\noindent Qu’est-ce qu’un monde ? \par
\noindent La famille \par
\noindent Y a-t-il des guerres justes ? \par
\noindent Le mot juste. \par
\noindent L’identité collective \par
\noindent La loi \par
\noindent Qu’est-ce qu’une question ? \par
\noindent Qui fait l’histoire ? \par
\noindent Qu’est-ce qu’une maladie ? \par
\noindent L’irrationnel \par
\noindent Qu’est-ce qu’un auteur ? \par
\noindent Qu’est-ce qui fait la force de la loi ? \par
\noindent La superstition \par
\noindent Peut-on s’en tenir au présent ? \par
\noindent L’emploi du temps \par
\noindent Y a-t-il des expériences métaphysiques ? \par
\noindent Le spectacle de la nature \par
\noindent Habiter le monde \par
\noindent L’état de droit \par
\noindent La servitude \par
\noindent La perspective \par
\noindent Qu’est-ce qu’un monstre ? \par
\noindent La reconnaissance \par
\noindent Le beau a-t-il une histoire ? \par
\noindent L’événement \par
\noindent Plaisir et douleur \par
\noindent L’interprétation \par
\noindent La solitude \par
\noindent L’illusion \par
\noindent L’observation \par
\noindent La raison d’Etat \par
\noindent L’harmonie \par
\noindent Justice et force \par
\noindent Le paysage \par
\noindent Apprend-on à voir ? \par
\noindent L’habitude \par
\noindent La simplicité \par
\noindent Faut-il se délivrer de la peur ? \par
\noindent Faut-il vouloir la transparence ? \par
\noindent Le langage est-il un instrument ? \par
\noindent L’identité personnelle \par
\noindent L’avocat du diable \par
\noindent Peut-il y avoir un droit de la guerre ? \par
\noindent Qu’est-ce qu’une croyance rationnelle ? \par
\noindent La désobéissance civile \par
\noindent L’ennemi \par
\noindent Qu’est-ce qu’une décision politique ? \par
\noindent Penser par soi-même \par
\noindent Être hors de soi \par
\noindent Pourquoi punir ? \par
\noindent L’artiste est-il un créateur ? \par
\noindent Peut-on tout exprimer ? \par
\noindent Cause et loi \par
\noindent Qu’est-ce qu’un mythe ? \par
\noindent Pouvons-nous être objectifs ? \par
\noindent L’étranger \par
\noindent L’imaginaire \par
\noindent Quel usage peut-on faire des fictions ? \par
\noindent Faire la paix \par
\noindent Le mouvement \par
\noindent La loi et la coutume \par
\noindent Quel est l’objet de l’amour ? \par
\noindent Qu’est-ce qu’une crise ? \par
\noindent Apprend-on à être artiste ? \par
\noindent L’oubli \par
\noindent L’amour de la vérité \par
\noindent Les œuvres d’art sont-elles éternelles ? \par
\noindent Le hasard \par
\noindent Peut-on être citoyen du monde ? \par
\noindent Y a-t-il des limites à la connaissance ? \par
\noindent L’apparence \par
\noindent La critique \par
\noindent La souveraineté peut-elle se partager ? \par
\noindent Qu’est-ce qui est réel ? \par
\noindent La justice sociale \par
\noindent L’immortalité \par
\end{multicols}

# ** L'art

# Pourquoi conserver les œuvres d'art ?

# L'art imite-t-il la nature ?

# L'éducation esthétique

# L'inspiration

# L'artiste sait-il ce qu'il fait ?

# L'art et la morale

# Le plaisir esthétique suppose-t-il une culture ?

# La virtuosité

# Qu'est-ce qu'une œuvre ratée ?

# Y a-t-il un progrès en art ?

# Le génie

# Le mauvais goût

# Arts de l'espace et arts du temps

# L'art engagé

# La pluralité des arts

# La vérité de l'œuvre d'art

# ** Logique et épistémologie

# Mécanisme et finalité

# Le symbolisme mathématique

# Le hasard n'est-il que la mesure de notre ignorance ?

# Comment choisir entre plusieurs hypothèses ?

# La logique nous apprend-elle quelque chose sur le langage ordinaire ?

# La causalité

# Sauver les phénomènes

# Les genres naturels

# Qu'est-ce qu'un nombre ?

# La cohérence est-elle un critère de vérité ?

# Des événements aléatoires peuvent-ils obéir à des lois ?

# L'intuition en mathématiques

# La contradiction

# La logique a-t-elle une histoire ?

# Y a-t-il plusieurs logiques ?

# La méthode

# Savoir et pouvoir

# ** La métaphysique

# L'impossible

# L'être et le temps

# Y a-t-il une connaissance métaphysique ?

# Seul le présent existe-t-il ?

# N'y a-t-il qu'un seul monde ?

# L'existence se démontre-t-elle ?

# Avons-nous une âme ?

# L'infinité du monde

# Que prouvent les preuves de l'existence de Dieu ?

# Le virtuel et le réel

# Le réel est-il rationnel ?

# Être et être pensé

# Penser sans corps

# Le miracle

# Logique et métaphysique

# Dieu a-t-il pu vouloir le mal ?

# ** La morale

# Sommes-nous responsables de notre passé ?

# Le repentir

# Peut-on conclure de l'être au devoir-être ?

# L'intolérable

# Le péché

# La beauté morale

# Peut-on vouloir le mal ?

# La morale peut-elle être fondée sur la science ?

# Y a-t-il un devoir d'être heureux ?

# La morale peut-elle se passer d'un fondement religieux ?

# La moralité n'est-elle que dressage ?

# La morale peut-elle être un calcul ?

# Le moi est-il haïssable ?

# ** La politique

# Guerre et politique

# La rationalité politique

# Qu'est-ce qu'un contre-pouvoir ?

# Le totalitarisme

# Que faut-il savoir pour gouverner ?

# Le législateur

# Le respect des institutions

# Les droits de l'homme sont-ils une abstraction ?

# La meilleure constitution

# A-t-on des droits contre l'État ?

# Qu'est-ce qu'un programme politique ?

# Y a-t-il des erreurs en politique ?

# ** Les sciences humaines

# Histoire et ethnologie

# Les sciences humaines permettent-elles de comprendre la vie d'un homme ?

# Les sciences humaines sont-elles dangereuses ?

# Expliquer et comprendre

# Qu'est-ce qui rend l'objectivité difficile dans les sciences humaines ?

# Sciences humaines et philosophie

# L'efficacité thérapeutique de la psychanalyse

# La psychanalyse est-elle une science ?

# Sciences humaines et liberté sont-elles compatibles ?

# Y a-t-il une causalité historique ?

# L'objectivité de l'historien

# L'arbitraire du signe

# Machines et mémoire

# Les sciences humaines permettent-elles d'affiner la notion de
# responsabilité ?

# L'économie a-t-elle des lois ?

# L'argent

# Y a-t-il un inconscient collectif ?

[1] Certains correcteurs sanctionnent explicitement d'un ou deux points
    une orthographe défaillante. Ceux qui ne le font pas sont souvent
    plus sévères : l'impression générale de négligence que délivre la
    copie les incite à en retirer implicitement bien plus.

[2] En termes aristotéliciens, une bonne définition doit non seulement
    énoncer le genre, mais également la différence spécifique (Aristote,
    /Topiques/, IV, 101b20 ; V, 101b35--102a20) ; c'est cette dernière
    qui fait souvent défaut.

# [3] Kant, /Logique/, §107.

[4] Kant, /Logique/, §109.

[5] Ce qui, au passage, montre l'utilité directe, pour la dissertation,
    de la logique : celle-ci n'est pas une discipline isolée du cursus,
    elle est proprement philosophique.

[6] Gilles-Gaston Granger, /Essai d'une philosophie du style/, Paris,
    Armand-Colin, Philosophies pour l'âge de la science, 1968, p. 7.

[7] Nietzsche, /Par-delà bien et mal/, §36.

[8] Ainsi, dans l'/Anthropologie/ (II, B), Kant définit la féminité par
    deux critères : la conservation de l'espèce (qui implique la crainte
    et la faiblesse), et l'affinement de la culture (qui implique la
    politesse et la tendance au bavardage).

* Footnotes

[fn:1] Ces sujets sont tirés du rapport du jury du concours oral pour
l'année 2018 de l'École normale supérieure de Paris
(http://www.ens.fr/sites/default/files/2018_al_philo_oral_epreuve_commune.pdf).
Les sujets ont été proposés par Fabienne Baghdassarian, François Calori,
Pascale Gillot, Laurent Lavaud, Baptiste Mélès et Pauline Nadrigny.

