#!/bin/zsh

org="BMeles-Codes_dissertation.org"
txt="BMeles-Codes_dissertation.txt"

pandoc "$org" -t markdown | \
    sed s@'.*KEYWORDS.*'@'_____________________________\nLISTE DES CODES DE CORRECTION UTILISÉS DANS LES COPIES\n(cf. http://baptiste.meles.free.fr/site/BMeles-Codes_dissertation.pdf)'@ | \
    sed s/'\\string'//g | \
    sed "s/\\\'/'/g" | \
    sed "s/\\\~/~/g" \
        >! "$txt"

cat "$txt" | xsel -i -b
